///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MobileBrowse
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MobileBrowseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c170b1fd-2acd-4f40-bf5b-1e061f45bf01")]
    public partial class MobileBrowseRepository : RepoGenBaseFolder
    {
        static MobileBrowseRepository instance = new MobileBrowseRepository();
        MobileBrowseRepositoryFolders.BrowserAppFolder _browser;
        MobileBrowseRepositoryFolders.DomAppFolder _dom;

        /// <summary>
        /// Gets the singleton class instance representing the MobileBrowseRepository element repository.
        /// </summary>
        [RepositoryFolder("c170b1fd-2acd-4f40-bf5b-1e061f45bf01")]
        public static MobileBrowseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MobileBrowseRepository() 
            : base("MobileBrowseRepository", "/", null, 0, false, "c170b1fd-2acd-4f40-bf5b-1e061f45bf01", ".\\RepositoryImages\\MobileBrowseRepositoryc170b1fd.rximgres")
        {
            _browser = new MobileBrowseRepositoryFolders.BrowserAppFolder(this);
            _dom = new MobileBrowseRepositoryFolders.DomAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c170b1fd-2acd-4f40-bf5b-1e061f45bf01")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Browser folder.
        /// </summary>
        [RepositoryFolder("2dc4a099-82b3-4f60-a552-7226bd06f91e")]
        public virtual MobileBrowseRepositoryFolders.BrowserAppFolder Browser
        {
            get { return _browser; }
        }

        /// <summary>
        /// The Dom folder.
        /// </summary>
        [RepositoryFolder("276f4afa-8924-4a69-aac4-2417855af386")]
        public virtual MobileBrowseRepositoryFolders.DomAppFolder Dom
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MobileBrowseRepositoryFolders
    {
        /// <summary>
        /// The BrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("2dc4a099-82b3-4f60-a552-7226bd06f91e")]
        public partial class BrowserAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Browser  folder.
            /// </summary>
            public BrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Browser", "/mobileapp[@title='ranorex.RxBrowser']", parentFolder, 300000, null, false, "2dc4a099-82b3-4f60-a552-7226bd06f91e", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2dc4a099-82b3-4f60-a552-7226bd06f91e")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2dc4a099-82b3-4f60-a552-7226bd06f91e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DomAppFolder folder.
        /// </summary>
        [RepositoryFolder("276f4afa-8924-4a69-aac4-2417855af386")]
        public partial class DomAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _serviciosdeitrInfo;
            RepoItemInfo _serviciosInfo;
            RepoItemInfo _designthinkingInfo;
            RepoItemInfo _testingInfo;
            RepoItemInfo _imgtagimgicontestingautomatizadosInfo;
            RepoItemInfo _testingautomatizadoInfo;

            /// <summary>
            /// Creates a new Dom  folder.
            /// </summary>
            public DomAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dom", "/mobileapp[@title='ranorex.RxBrowser']//dom", parentFolder, 300000, null, false, "276f4afa-8924-4a69-aac4-2417855af386", "")
            {
                _serviciosdeitrInfo = new RepoItemInfo(this, "ServiciosDeITR", ".//div[#'navbarBasicExample']//a[@innertext='Servicios' and @visible='true']", 30000, null, "347790ea-f050-416d-a441-2c3b4a440299");
                _serviciosInfo = new RepoItemInfo(this, "Servicios", "body/section[1]//h1[@innertext='Servicios' and @visible='true']", 30000, null, "06616a18-63fe-4b4b-8b3b-82cfdb1d49d2");
                _designthinkingInfo = new RepoItemInfo(this, "DesignThinking", ".//div[#'servicios']/div/div/div[4]//a[@href>'http://www.somositr.com/t']/div/div[1]/?/?/img[@alt='Design Thinking']", 30000, null, "e8ed33e8-7443-4b1a-8adf-4c59de4be107");
                _testingInfo = new RepoItemInfo(this, "Testing", "body/section[1]//h1[@innertext='Testing' and @visible='true']", 30000, null, "3fb4fbee-4ea9-469d-8bac-3cf9f440a649");
                _imgtagimgicontestingautomatizadosInfo = new RepoItemInfo(this, "ImgTagImgIconTestingAutomatizadoS", "body/div[1]/div/div/div/div/div/div[2]/div/div[1]/?/?/img[@alt>'../img/icon/testing/autom']", 30000, null, "cf450893-288f-4b07-8d71-4157ba2e0a57");
                _testingautomatizadoInfo = new RepoItemInfo(this, "TestingAutomatizado", "body/div[1]/div/div/div/div/div/div[2]/div/div[2]/h4[@innertext='Testing automatizado' and @visible='true']", 30000, null, "4544df06-06e4-4113-86ea-45ceb3acd554");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("276f4afa-8924-4a69-aac4-2417855af386")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("276f4afa-8924-4a69-aac4-2417855af386")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ServiciosDeITR item.
            /// </summary>
            [RepositoryItem("347790ea-f050-416d-a441-2c3b4a440299")]
            public virtual Ranorex.ATag ServiciosDeITR
            {
                get
                {
                    return _serviciosdeitrInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ServiciosDeITR item info.
            /// </summary>
            [RepositoryItemInfo("347790ea-f050-416d-a441-2c3b4a440299")]
            public virtual RepoItemInfo ServiciosDeITRInfo
            {
                get
                {
                    return _serviciosdeitrInfo;
                }
            }

            /// <summary>
            /// The Servicios item.
            /// </summary>
            [RepositoryItem("06616a18-63fe-4b4b-8b3b-82cfdb1d49d2")]
            public virtual Ranorex.H1Tag Servicios
            {
                get
                {
                    return _serviciosInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Servicios item info.
            /// </summary>
            [RepositoryItemInfo("06616a18-63fe-4b4b-8b3b-82cfdb1d49d2")]
            public virtual RepoItemInfo ServiciosInfo
            {
                get
                {
                    return _serviciosInfo;
                }
            }

            /// <summary>
            /// The DesignThinking item.
            /// </summary>
            [RepositoryItem("e8ed33e8-7443-4b1a-8adf-4c59de4be107")]
            public virtual Ranorex.ImgTag DesignThinking
            {
                get
                {
                    return _designthinkingInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The DesignThinking item info.
            /// </summary>
            [RepositoryItemInfo("e8ed33e8-7443-4b1a-8adf-4c59de4be107")]
            public virtual RepoItemInfo DesignThinkingInfo
            {
                get
                {
                    return _designthinkingInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("3fb4fbee-4ea9-469d-8bac-3cf9f440a649")]
            public virtual Ranorex.H1Tag Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("3fb4fbee-4ea9-469d-8bac-3cf9f440a649")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }

            /// <summary>
            /// The ImgTagImgIconTestingAutomatizadoS item.
            /// </summary>
            [RepositoryItem("cf450893-288f-4b07-8d71-4157ba2e0a57")]
            public virtual Ranorex.ImgTag ImgTagImgIconTestingAutomatizadoS
            {
                get
                {
                    return _imgtagimgicontestingautomatizadosInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgTagImgIconTestingAutomatizadoS item info.
            /// </summary>
            [RepositoryItemInfo("cf450893-288f-4b07-8d71-4157ba2e0a57")]
            public virtual RepoItemInfo ImgTagImgIconTestingAutomatizadoSInfo
            {
                get
                {
                    return _imgtagimgicontestingautomatizadosInfo;
                }
            }

            /// <summary>
            /// The TestingAutomatizado item.
            /// </summary>
            [RepositoryItem("4544df06-06e4-4113-86ea-45ceb3acd554")]
            public virtual Ranorex.H4Tag TestingAutomatizado
            {
                get
                {
                    return _testingautomatizadoInfo.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The TestingAutomatizado item info.
            /// </summary>
            [RepositoryItemInfo("4544df06-06e4-4113-86ea-45ceb3acd554")]
            public virtual RepoItemInfo TestingAutomatizadoInfo
            {
                get
                {
                    return _testingautomatizadoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
