///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Desktop.Acciones
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MoverYBorrar recording.
    /// </summary>
    [TestModule("01b9ab7f-c14a-4a88-aee1-db010dc1e911", ModuleType.Recording, 1)]
    public partial class MoverYBorrar : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Desktop.DesktopRepository repository.
        /// </summary>
        public static global::Desktop.DesktopRepository repo = global::Desktop.DesktopRepository.Instance;

        static MoverYBorrar instance = new MoverYBorrar();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MoverYBorrar()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MoverYBorrar Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Database' at 24;9.", repo.MainForm.DatabaseInfo, new RecordItemIndex(0));
            repo.MainForm.Database.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MainForm.PruebaAutomatizacion' at CenterLeft.", repo.MainForm.PruebaAutomatizacionInfo, new RecordItemIndex(1));
            repo.MainForm.PruebaAutomatizacion.Click(System.Windows.Forms.MouseButtons.Right, Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.Rearrange' at Center.", repo.KeePass.RearrangeInfo, new RecordItemIndex(2));
            repo.KeePass.Rearrange.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.MoveToGroup' at Center.", repo.KeePass.MoveToGroupInfo, new RecordItemIndex(3));
            repo.KeePass.MoveToGroup.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.MenuItemGeneral' at Center.", repo.KeePass.MenuItemGeneralInfo, new RecordItemIndex(4));
            repo.KeePass.MenuItemGeneral.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.General' at 22;8.", repo.MainForm.GeneralInfo, new RecordItemIndex(5));
            repo.MainForm.General.Click("22;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'MainForm.PruebaAutomatizacion'", repo.MainForm.PruebaAutomatizacionInfo, new ActionTimeout(30000), new RecordItemIndex(6));
            repo.MainForm.PruebaAutomatizacionInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.PruebaAutomatizacion' at Center.", repo.MainForm.PruebaAutomatizacionInfo, new RecordItemIndex(8));
            repo.MainForm.PruebaAutomatizacion.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'MainForm.Text'", repo.MainForm.TextInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.MainForm.TextInfo.WaitForExists(30000);
            
            // Eliminacion del usuario
            Report.Log(ReportLevel.Info, "Section", "Eliminacion del usuario", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}'.", new RecordItemIndex(11));
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'KeePassMsgs.MoverPapelera'", repo.KeePassMsgs.MoverPapeleraInfo, new ActionTimeout(30000), new RecordItemIndex(12));
            repo.KeePassMsgs.MoverPapeleraInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePassMsgs.ButtonYes' at Center.", repo.KeePassMsgs.ButtonYesInfo, new RecordItemIndex(13));
            repo.KeePassMsgs.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            // Vaciar Papelera de Reciclaje
            Report.Log(ReportLevel.Info, "Section", "Vaciar Papelera de Reciclaje", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MainForm.RecycleBin' at 29;10.", repo.MainForm.RecycleBinInfo, new RecordItemIndex(15));
            repo.MainForm.RecycleBin.Click(System.Windows.Forms.MouseButtons.Right, "29;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.EmptyRecycleBin' at 59;9.", repo.KeePass.EmptyRecycleBinInfo, new RecordItemIndex(16));
            repo.KeePass.EmptyRecycleBin.Click("59;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'KeePassMsgs.EliminaPapelera'", repo.KeePassMsgs.EliminaPapeleraInfo, new ActionTimeout(30000), new RecordItemIndex(17));
            repo.KeePassMsgs.EliminaPapeleraInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePassMsgs.ButtonDelete' at Center.", repo.KeePassMsgs.ButtonDeleteInfo, new RecordItemIndex(18));
            repo.KeePassMsgs.ButtonDelete.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Database' at Center.", repo.MainForm.DatabaseInfo, new RecordItemIndex(19));
            repo.MainForm.Database.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
