///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Mobile
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MobileRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("baf33119-7223-4443-a93b-3a30a6b2fc25")]
    public partial class MobileRepository : RepoGenBaseFolder
    {
        static MobileRepository instance = new MobileRepository();
        MobileRepositoryFolders.ComAndroidKeepassAppFolder _comandroidkeepass;

        /// <summary>
        /// Gets the singleton class instance representing the MobileRepository element repository.
        /// </summary>
        [RepositoryFolder("baf33119-7223-4443-a93b-3a30a6b2fc25")]
        public static MobileRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MobileRepository() 
            : base("MobileRepository", "/", null, 0, false, "baf33119-7223-4443-a93b-3a30a6b2fc25", ".\\RepositoryImages\\MobileRepositorybaf33119.rximgres")
        {
            _comandroidkeepass = new MobileRepositoryFolders.ComAndroidKeepassAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("baf33119-7223-4443-a93b-3a30a6b2fc25")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComAndroidKeepass folder.
        /// </summary>
        [RepositoryFolder("35ecf492-239f-44e8-9dca-52d270c454ad")]
        public virtual MobileRepositoryFolders.ComAndroidKeepassAppFolder ComAndroidKeepass
        {
            get { return _comandroidkeepass; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MobileRepositoryFolders
    {
        /// <summary>
        /// The ComAndroidKeepassAppFolder folder.
        /// </summary>
        [RepositoryFolder("35ecf492-239f-44e8-9dca-52d270c454ad")]
        public partial class ComAndroidKeepassAppFolder : RepoGenBaseFolder
        {
            MobileRepositoryFolders.ContentFolder _content;
            MobileRepositoryFolders.Content1Folder _content1;
            MobileRepositoryFolders.GeneratePasswordActivityFolder _generatepasswordactivity;
            RepoItemInfo _openInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _passokInfo;
            RepoItemInfo _entrysaveInfo;

            /// <summary>
            /// Creates a new ComAndroidKeepass  folder.
            /// </summary>
            public ComAndroidKeepassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComAndroidKeepass", "/mobileapp[@title='com.android.keepass']", parentFolder, 30000, null, false, "35ecf492-239f-44e8-9dca-52d270c454ad", "")
            {
                _content = new MobileRepositoryFolders.ContentFolder(this);
                _content1 = new MobileRepositoryFolders.Content1Folder(this);
                _generatepasswordactivity = new MobileRepositoryFolders.GeneratePasswordActivityFolder(this);
                _openInfo = new RepoItemInfo(this, "Open", "form[@title='FileSelectActivity']/container[@rid='content']//button[@resourceid='R.string.menu_open']", 30000, null, "fe3a9266-692a-4334-8a43-d3b4c9158a5b");
                _passwordInfo = new RepoItemInfo(this, "Password", "form[@title='PasswordActivity']//text[@rid='password']", 30000, null, "4fbc52b4-1289-49ed-a4f3-e74ed4a6176c");
                _passokInfo = new RepoItemInfo(this, "PassOk", "form[@title='PasswordActivity']//button[@resourceid='R.string.accept']", 30000, null, "b54d3268-4b45-45fa-adbb-14f8146d0819");
                _entrysaveInfo = new RepoItemInfo(this, "EntrySave", "form[@title='EntryEditActivityV3']//button[@resourceid='R.string.entry_save']", 30000, null, "64cd171e-3c9e-4a99-9e1a-9d211a87d498");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("35ecf492-239f-44e8-9dca-52d270c454ad")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("35ecf492-239f-44e8-9dca-52d270c454ad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("fe3a9266-692a-4334-8a43-d3b4c9158a5b")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("fe3a9266-692a-4334-8a43-d3b4c9158a5b")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("4fbc52b4-1289-49ed-a4f3-e74ed4a6176c")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("4fbc52b4-1289-49ed-a4f3-e74ed4a6176c")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The PassOk item.
            /// </summary>
            [RepositoryItem("b54d3268-4b45-45fa-adbb-14f8146d0819")]
            public virtual Ranorex.Button PassOk
            {
                get
                {
                    return _passokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PassOk item info.
            /// </summary>
            [RepositoryItemInfo("b54d3268-4b45-45fa-adbb-14f8146d0819")]
            public virtual RepoItemInfo PassOkInfo
            {
                get
                {
                    return _passokInfo;
                }
            }

            /// <summary>
            /// The EntrySave item.
            /// </summary>
            [RepositoryItem("64cd171e-3c9e-4a99-9e1a-9d211a87d498")]
            public virtual Ranorex.Button EntrySave
            {
                get
                {
                    return _entrysaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EntrySave item info.
            /// </summary>
            [RepositoryItemInfo("64cd171e-3c9e-4a99-9e1a-9d211a87d498")]
            public virtual RepoItemInfo EntrySaveInfo
            {
                get
                {
                    return _entrysaveInfo;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("fb005864-48a2-4b7c-bc04-ca312ac2a7f9")]
            public virtual MobileRepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }

            /// <summary>
            /// The Content1 folder.
            /// </summary>
            [RepositoryFolder("2818f590-2e4a-4e55-b546-bd290920833a")]
            public virtual MobileRepositoryFolders.Content1Folder Content1
            {
                get { return _content1; }
            }

            /// <summary>
            /// The GeneratePasswordActivity folder.
            /// </summary>
            [RepositoryFolder("f7be896b-f8cd-4573-9ae4-7fffd1077e58")]
            public virtual MobileRepositoryFolders.GeneratePasswordActivityFolder GeneratePasswordActivity
            {
                get { return _generatepasswordactivity; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("fb005864-48a2-4b7c-bc04-ca312ac2a7f9")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconInfo;
            RepoItemInfo _raizInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _addentryInfo;
            RepoItemInfo _itrmailInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", "form[@title='GroupActivityV3']/container[@rid='content']", parentFolder, 30000, null, false, "fb005864-48a2-4b7c-bc04-ca312ac2a7f9", "")
            {
                _iconInfo = new RepoItemInfo(this, "Icon", ".//androidelement[@rid='group_header']//picture[@resourceid='R.drawable.ic19']", 30000, null, "5190a783-ec6f-4589-8856-69447476c4c7");
                _raizInfo = new RepoItemInfo(this, "Raiz", ".//androidelement[@rid='group_header']//text[@resourceid='R.string.root']", 30000, null, "8370ea57-f38f-4f74-ae6c-4204a95df30c");
                _emailInfo = new RepoItemInfo(this, "EMail", ".//list[@rid='list']/?/?/table/?/?/text[@caption='eMail']", 30000, null, "04cbea46-4de3-4988-8c78-7e1ead62fb53");
                _addentryInfo = new RepoItemInfo(this, "AddEntry", ".//button[@resourceid='R.string.add_entry']", 30000, null, "a82ac52a-1e35-4309-a521-1d06aaadd792");
                _itrmailInfo = new RepoItemInfo(this, "ITRMail", ".//list[@rid='list']/?/?/table/?/?/text[@caption='ITR Mail']", 30000, null, "dc856ba4-74cd-4741-b5f6-602a320edc64");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fb005864-48a2-4b7c-bc04-ca312ac2a7f9")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fb005864-48a2-4b7c-bc04-ca312ac2a7f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Icon item.
            /// </summary>
            [RepositoryItem("5190a783-ec6f-4589-8856-69447476c4c7")]
            public virtual Ranorex.Picture Icon
            {
                get
                {
                    return _iconInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Icon item info.
            /// </summary>
            [RepositoryItemInfo("5190a783-ec6f-4589-8856-69447476c4c7")]
            public virtual RepoItemInfo IconInfo
            {
                get
                {
                    return _iconInfo;
                }
            }

            /// <summary>
            /// The Raiz item.
            /// </summary>
            [RepositoryItem("8370ea57-f38f-4f74-ae6c-4204a95df30c")]
            public virtual Ranorex.Text Raiz
            {
                get
                {
                    return _raizInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Raiz item info.
            /// </summary>
            [RepositoryItemInfo("8370ea57-f38f-4f74-ae6c-4204a95df30c")]
            public virtual RepoItemInfo RaizInfo
            {
                get
                {
                    return _raizInfo;
                }
            }

            /// <summary>
            /// The EMail item.
            /// </summary>
            [RepositoryItem("04cbea46-4de3-4988-8c78-7e1ead62fb53")]
            public virtual Ranorex.Text EMail
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EMail item info.
            /// </summary>
            [RepositoryItemInfo("04cbea46-4de3-4988-8c78-7e1ead62fb53")]
            public virtual RepoItemInfo EMailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("a82ac52a-1e35-4309-a521-1d06aaadd792")]
            public virtual Ranorex.Button AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("a82ac52a-1e35-4309-a521-1d06aaadd792")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The ITRMail item.
            /// </summary>
            [RepositoryItem("dc856ba4-74cd-4741-b5f6-602a320edc64")]
            public virtual Ranorex.Text ITRMail
            {
                get
                {
                    return _itrmailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ITRMail item info.
            /// </summary>
            [RepositoryItemInfo("dc856ba4-74cd-4741-b5f6-602a320edc64")]
            public virtual RepoItemInfo ITRMailInfo
            {
                get
                {
                    return _itrmailInfo;
                }
            }
        }

        /// <summary>
        /// The Content1Folder folder.
        /// </summary>
        [RepositoryFolder("2818f590-2e4a-4e55-b546-bd290920833a")]
        public partial class Content1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _iconbuttonInfo;
            RepoItemInfo _entrytitleInfo;
            RepoItemInfo _entryusernameInfo;
            RepoItemInfo _entryurlInfo;
            RepoItemInfo _generatebuttonInfo;

            /// <summary>
            /// Creates a new Content1  folder.
            /// </summary>
            public Content1Folder(RepoGenBaseFolder parentFolder) :
                    base("Content1", "form[@title='EntryEditActivityV3']/container[@rid='content']", parentFolder, 30000, null, false, "2818f590-2e4a-4e55-b546-bd290920833a", "")
            {
                _iconbuttonInfo = new RepoItemInfo(this, "IconButton", ".//button[@resourceid='R.drawable.ic00']", 30000, null, "25698c09-1926-4c7e-9b64-b1890d666199");
                _entrytitleInfo = new RepoItemInfo(this, "EntryTitle", ".//text[@rid='entry_title']", 30000, null, "bacfdd95-eac6-458a-b2b7-f58bdc4fe2a7");
                _entryusernameInfo = new RepoItemInfo(this, "EntryUserName", ".//text[@rid='entry_user_name']", 30000, null, "fe690df6-af47-4c7c-bfa0-15a5ceaf6494");
                _entryurlInfo = new RepoItemInfo(this, "EntryUrl", ".//text[@rid='entry_url']", 30000, null, "c9d639ab-5111-4396-a6f5-1361f876ec50");
                _generatebuttonInfo = new RepoItemInfo(this, "GenerateButton", ".//button[@resourceid='R.string.ellipsis']", 30000, null, "dbbed1f4-1bad-4ba2-a5da-73c018a46b73");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2818f590-2e4a-4e55-b546-bd290920833a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2818f590-2e4a-4e55-b546-bd290920833a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IconButton item.
            /// </summary>
            [RepositoryItem("25698c09-1926-4c7e-9b64-b1890d666199")]
            public virtual Ranorex.Button IconButton
            {
                get
                {
                    return _iconbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The IconButton item info.
            /// </summary>
            [RepositoryItemInfo("25698c09-1926-4c7e-9b64-b1890d666199")]
            public virtual RepoItemInfo IconButtonInfo
            {
                get
                {
                    return _iconbuttonInfo;
                }
            }

            /// <summary>
            /// The EntryTitle item.
            /// </summary>
            [RepositoryItem("bacfdd95-eac6-458a-b2b7-f58bdc4fe2a7")]
            public virtual Ranorex.Text EntryTitle
            {
                get
                {
                    return _entrytitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryTitle item info.
            /// </summary>
            [RepositoryItemInfo("bacfdd95-eac6-458a-b2b7-f58bdc4fe2a7")]
            public virtual RepoItemInfo EntryTitleInfo
            {
                get
                {
                    return _entrytitleInfo;
                }
            }

            /// <summary>
            /// The EntryUserName item.
            /// </summary>
            [RepositoryItem("fe690df6-af47-4c7c-bfa0-15a5ceaf6494")]
            public virtual Ranorex.Text EntryUserName
            {
                get
                {
                    return _entryusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryUserName item info.
            /// </summary>
            [RepositoryItemInfo("fe690df6-af47-4c7c-bfa0-15a5ceaf6494")]
            public virtual RepoItemInfo EntryUserNameInfo
            {
                get
                {
                    return _entryusernameInfo;
                }
            }

            /// <summary>
            /// The EntryUrl item.
            /// </summary>
            [RepositoryItem("c9d639ab-5111-4396-a6f5-1361f876ec50")]
            public virtual Ranorex.Text EntryUrl
            {
                get
                {
                    return _entryurlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryUrl item info.
            /// </summary>
            [RepositoryItemInfo("c9d639ab-5111-4396-a6f5-1361f876ec50")]
            public virtual RepoItemInfo EntryUrlInfo
            {
                get
                {
                    return _entryurlInfo;
                }
            }

            /// <summary>
            /// The GenerateButton item.
            /// </summary>
            [RepositoryItem("dbbed1f4-1bad-4ba2-a5da-73c018a46b73")]
            public virtual Ranorex.Button GenerateButton
            {
                get
                {
                    return _generatebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GenerateButton item info.
            /// </summary>
            [RepositoryItemInfo("dbbed1f4-1bad-4ba2-a5da-73c018a46b73")]
            public virtual RepoItemInfo GenerateButtonInfo
            {
                get
                {
                    return _generatebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The GeneratePasswordActivityFolder folder.
        /// </summary>
        [RepositoryFolder("f7be896b-f8cd-4573-9ae4-7fffd1077e58")]
        public partial class GeneratePasswordActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _acceptbuttonInfo;
            RepoItemInfo _btnlength12Info;
            RepoItemInfo _generatepasswordbuttonInfo;

            /// <summary>
            /// Creates a new GeneratePasswordActivity  folder.
            /// </summary>
            public GeneratePasswordActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("GeneratePasswordActivity", "form[@title='GeneratePasswordActivity']", parentFolder, 30000, null, false, "f7be896b-f8cd-4573-9ae4-7fffd1077e58", "")
            {
                _acceptbuttonInfo = new RepoItemInfo(this, "AcceptButton", ".//button[@resourceid='R.string.accept']", 30000, null, "5f6fd54d-84ea-4be5-98fe-f0b5de690d7b");
                _btnlength12Info = new RepoItemInfo(this, "BtnLength12", ".//container[@rid='ScrollView']/?/?/button[@resourceid='R.string.generate_12']", 30000, null, "4d1c18ef-57d6-478b-b492-2dfa00bef85e");
                _generatepasswordbuttonInfo = new RepoItemInfo(this, "GeneratePasswordButton", ".//container[@rid='ScrollView']/?/?/button[@resourceid='R.string.generate_password']", 30000, null, "6123ae89-db07-4250-9de6-998ee471e599");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7be896b-f8cd-4573-9ae4-7fffd1077e58")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7be896b-f8cd-4573-9ae4-7fffd1077e58")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AcceptButton item.
            /// </summary>
            [RepositoryItem("5f6fd54d-84ea-4be5-98fe-f0b5de690d7b")]
            public virtual Ranorex.Button AcceptButton
            {
                get
                {
                    return _acceptbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AcceptButton item info.
            /// </summary>
            [RepositoryItemInfo("5f6fd54d-84ea-4be5-98fe-f0b5de690d7b")]
            public virtual RepoItemInfo AcceptButtonInfo
            {
                get
                {
                    return _acceptbuttonInfo;
                }
            }

            /// <summary>
            /// The BtnLength12 item.
            /// </summary>
            [RepositoryItem("4d1c18ef-57d6-478b-b492-2dfa00bef85e")]
            public virtual Ranorex.Button BtnLength12
            {
                get
                {
                    return _btnlength12Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnLength12 item info.
            /// </summary>
            [RepositoryItemInfo("4d1c18ef-57d6-478b-b492-2dfa00bef85e")]
            public virtual RepoItemInfo BtnLength12Info
            {
                get
                {
                    return _btnlength12Info;
                }
            }

            /// <summary>
            /// The GeneratePasswordButton item.
            /// </summary>
            [RepositoryItem("6123ae89-db07-4250-9de6-998ee471e599")]
            public virtual Ranorex.Button GeneratePasswordButton
            {
                get
                {
                    return _generatepasswordbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GeneratePasswordButton item info.
            /// </summary>
            [RepositoryItemInfo("6123ae89-db07-4250-9de6-998ee471e599")]
            public virtual RepoItemInfo GeneratePasswordButtonInfo
            {
                get
                {
                    return _generatepasswordbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
