///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PruebaOneDrive
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PruebaOneDriveRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f575972e-29da-43e5-81d3-98a25a6ca7ab")]
    public partial class PruebaOneDriveRepository : RepoGenBaseFolder
    {
        static PruebaOneDriveRepository instance = new PruebaOneDriveRepository();
        PruebaOneDriveRepositoryFolders.SignInMicrosoftOneDriveAppFolder _signinmicrosoftonedrive;
        PruebaOneDriveRepositoryFolders.SignInMicrosoftOneDriver_COFAppFolder _signinmicrosoftonedriver_cof;
        PruebaOneDriveRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder _personalcloudstoragemicrosoftonedri;
        PruebaOneDriveRepositoryFolders.AbrirAppFolder _abrir;

        /// <summary>
        /// Gets the singleton class instance representing the PruebaOneDriveRepository element repository.
        /// </summary>
        [RepositoryFolder("f575972e-29da-43e5-81d3-98a25a6ca7ab")]
        public static PruebaOneDriveRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PruebaOneDriveRepository() 
            : base("PruebaOneDriveRepository", "/", null, 0, false, "f575972e-29da-43e5-81d3-98a25a6ca7ab", ".\\RepositoryImages\\PruebaOneDriveRepositoryf575972e.rximgres")
        {
            _signinmicrosoftonedrive = new PruebaOneDriveRepositoryFolders.SignInMicrosoftOneDriveAppFolder(this);
            _signinmicrosoftonedriver_cof = new PruebaOneDriveRepositoryFolders.SignInMicrosoftOneDriver_COFAppFolder(this);
            _personalcloudstoragemicrosoftonedri = new PruebaOneDriveRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder(this);
            _abrir = new PruebaOneDriveRepositoryFolders.AbrirAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f575972e-29da-43e5-81d3-98a25a6ca7ab")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SignInMicrosoftOneDrive folder.
        /// </summary>
        [RepositoryFolder("2a4f3a24-df99-492b-ba88-507cfc2b28f8")]
        public virtual PruebaOneDriveRepositoryFolders.SignInMicrosoftOneDriveAppFolder SignInMicrosoftOneDrive
        {
            get { return _signinmicrosoftonedrive; }
        }

        /// <summary>
        /// The SignInMicrosoftOneDriver_COF folder.
        /// </summary>
        [RepositoryFolder("d4f4bec1-a29a-4b36-add8-c4c886887ff9")]
        public virtual PruebaOneDriveRepositoryFolders.SignInMicrosoftOneDriver_COFAppFolder SignInMicrosoftOneDriver_COF
        {
            get { return _signinmicrosoftonedriver_cof; }
        }

        /// <summary>
        /// The PersonalCloudStorageMicrosoftOneDri folder.
        /// </summary>
        [RepositoryFolder("71c3c745-a87c-4440-a406-daa0e93fa6f5")]
        public virtual PruebaOneDriveRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder PersonalCloudStorageMicrosoftOneDri
        {
            get { return _personalcloudstoragemicrosoftonedri; }
        }

        /// <summary>
        /// The Abrir folder.
        /// </summary>
        [RepositoryFolder("1362989b-eaf3-4e1f-9238-2790078eaa5c")]
        public virtual PruebaOneDriveRepositoryFolders.AbrirAppFolder Abrir
        {
            get { return _abrir; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PruebaOneDriveRepositoryFolders
    {
        /// <summary>
        /// The SignInMicrosoftOneDriveAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a4f3a24-df99-492b-ba88-507cfc2b28f8")]
        public partial class SignInMicrosoftOneDriveAppFolder : RepoGenBaseFolder
        {
            PruebaOneDriveRepositoryFolders.SomeDivTagFolder _somedivtag;
            PruebaOneDriveRepositoryFolders.AppRootFolder _approot;
            PruebaOneDriveRepositoryFolders.OdBasePageOdBasePageLeftNavVisibleOFolder _odbasepageodbasepageleftnavvisibleo;
            RepoItemInfo _lbl_signinInfo;
            RepoItemInfo _passwdInfo;
            RepoItemInfo _btn_signinInfo;
            RepoItemInfo _almacenpersonalInfo;
            RepoItemInfo _archivosInfo;
            RepoItemInfo _carpetaInfo;
            RepoItemInfo _lbl_carpetaInfo;
            RepoItemInfo _lbl_vaciarpapeleraInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _mecontrolsignoutlinkInfo;

            /// <summary>
            /// Creates a new SignInMicrosoftOneDrive  folder.
            /// </summary>
            public SignInMicrosoftOneDriveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInMicrosoftOneDrive", "/dom[@domain~'live.com']", parentFolder, 30000, null, false, "2a4f3a24-df99-492b-ba88-507cfc2b28f8", "")
            {
                _somedivtag = new PruebaOneDriveRepositoryFolders.SomeDivTagFolder(this);
                _approot = new PruebaOneDriveRepositoryFolders.AppRootFolder(this);
                _odbasepageodbasepageleftnavvisibleo = new PruebaOneDriveRepositoryFolders.OdBasePageOdBasePageLeftNavVisibleOFolder(this);
                _lbl_signinInfo = new RepoItemInfo(this, "lbl_SignIn", ".//section[#'mainContent']/iframe[@src='https://odc.officeapps.live.com/odc/v2.0/hrd?rs=en-us&Ver=16&app=23&p=6&hm=0']/body/div[2]//h1[@innertext='Sign in']", 30000, null, "5eb8b652-e534-4e06-9dbd-38530483d1a7");
                _passwdInfo = new RepoItemInfo(this, "Passwd", "body/?/?/form[@name='f1']/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div[2]//input[@name='passwd']", 30000, null, "5124834e-f452-4bdd-b1e5-ca22226f906b");
                _btn_signinInfo = new RepoItemInfo(this, "btn_SignIn", ".//input[#'idSIButton9']", 30000, null, "5d8a214e-bce0-44d8-9abd-7b2d31b45ad6");
                _almacenpersonalInfo = new RepoItemInfo(this, "AlmacenPersonal", ".//div[#'appRoot']/div/div[2]/div[5]/main/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div/div[1]/div/div/div/a[@href>'https://onedrive.live.com']/span[3]/span[1]//span[@innertext='Almacén personal']", 30000, null, "11edaa83-03ac-4588-8b47-34c396112219");
                _archivosInfo = new RepoItemInfo(this, "Archivos", "body//ul/li[@title='Archivos']/button[@title='Archivos']//span[@innertext='Archivos']", 30000, null, "199aabc7-6056-487e-8ee9-80a8177b5c81");
                _carpetaInfo = new RepoItemInfo(this, "Carpeta", "body//div//ul/li[@title='Carpeta']/button[@title='Carpeta']//span[@innertext='Carpeta' and @visible='true']", 30000, null, "cb1e73c7-36b6-4a8c-901f-32a00109098a");
                _lbl_carpetaInfo = new RepoItemInfo(this, "lbl_Carpeta", ".//p[#'od-Dialog-title']", 30000, null, "35b1b0c4-d153-4713-b20e-8f7650e8d961");
                _lbl_vaciarpapeleraInfo = new RepoItemInfo(this, "lbl_VaciarPapelera", ".//p[@innertext='Vaciar papelera de reciclaje']", 30000, null, "33b1d8ea-62cc-43aa-9f41-61f6183242a8");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'od-Dialog-content']//input[@type='text']", 30000, null, "caa45446-3d79-4801-ad33-1a66433276b1");
                _mecontrolsignoutlinkInfo = new RepoItemInfo(this, "MeControlSignoutLink", ".//a[#'meControlSignoutLink']", 30000, null, "7a3d0984-c2aa-45bd-b98b-93d9f6e68a44");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a4f3a24-df99-492b-ba88-507cfc2b28f8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a4f3a24-df99-492b-ba88-507cfc2b28f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lbl_SignIn item.
            /// </summary>
            [RepositoryItem("5eb8b652-e534-4e06-9dbd-38530483d1a7")]
            public virtual Ranorex.H1Tag lbl_SignIn
            {
                get
                {
                    return _lbl_signinInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The lbl_SignIn item info.
            /// </summary>
            [RepositoryItemInfo("5eb8b652-e534-4e06-9dbd-38530483d1a7")]
            public virtual RepoItemInfo lbl_SignInInfo
            {
                get
                {
                    return _lbl_signinInfo;
                }
            }

            /// <summary>
            /// The Passwd item.
            /// </summary>
            [RepositoryItem("5124834e-f452-4bdd-b1e5-ca22226f906b")]
            public virtual Ranorex.InputTag Passwd
            {
                get
                {
                    return _passwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Passwd item info.
            /// </summary>
            [RepositoryItemInfo("5124834e-f452-4bdd-b1e5-ca22226f906b")]
            public virtual RepoItemInfo PasswdInfo
            {
                get
                {
                    return _passwdInfo;
                }
            }

            /// <summary>
            /// The btn_SignIn item.
            /// </summary>
            [RepositoryItem("5d8a214e-bce0-44d8-9abd-7b2d31b45ad6")]
            public virtual Ranorex.InputTag btn_SignIn
            {
                get
                {
                    return _btn_signinInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btn_SignIn item info.
            /// </summary>
            [RepositoryItemInfo("5d8a214e-bce0-44d8-9abd-7b2d31b45ad6")]
            public virtual RepoItemInfo btn_SignInInfo
            {
                get
                {
                    return _btn_signinInfo;
                }
            }

            /// <summary>
            /// The AlmacenPersonal item.
            /// </summary>
            [RepositoryItem("11edaa83-03ac-4588-8b47-34c396112219")]
            public virtual Ranorex.SpanTag AlmacenPersonal
            {
                get
                {
                    return _almacenpersonalInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AlmacenPersonal item info.
            /// </summary>
            [RepositoryItemInfo("11edaa83-03ac-4588-8b47-34c396112219")]
            public virtual RepoItemInfo AlmacenPersonalInfo
            {
                get
                {
                    return _almacenpersonalInfo;
                }
            }

            /// <summary>
            /// The Archivos item.
            /// </summary>
            [RepositoryItem("199aabc7-6056-487e-8ee9-80a8177b5c81")]
            public virtual Ranorex.SpanTag Archivos
            {
                get
                {
                    return _archivosInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Archivos item info.
            /// </summary>
            [RepositoryItemInfo("199aabc7-6056-487e-8ee9-80a8177b5c81")]
            public virtual RepoItemInfo ArchivosInfo
            {
                get
                {
                    return _archivosInfo;
                }
            }

            /// <summary>
            /// The Carpeta item.
            /// </summary>
            [RepositoryItem("cb1e73c7-36b6-4a8c-901f-32a00109098a")]
            public virtual Ranorex.SpanTag Carpeta
            {
                get
                {
                    return _carpetaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Carpeta item info.
            /// </summary>
            [RepositoryItemInfo("cb1e73c7-36b6-4a8c-901f-32a00109098a")]
            public virtual RepoItemInfo CarpetaInfo
            {
                get
                {
                    return _carpetaInfo;
                }
            }

            /// <summary>
            /// The lbl_Carpeta item.
            /// </summary>
            [RepositoryItem("35b1b0c4-d153-4713-b20e-8f7650e8d961")]
            public virtual Ranorex.PTag lbl_Carpeta
            {
                get
                {
                    return _lbl_carpetaInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The lbl_Carpeta item info.
            /// </summary>
            [RepositoryItemInfo("35b1b0c4-d153-4713-b20e-8f7650e8d961")]
            public virtual RepoItemInfo lbl_CarpetaInfo
            {
                get
                {
                    return _lbl_carpetaInfo;
                }
            }

            /// <summary>
            /// The lbl_VaciarPapelera item.
            /// </summary>
            [RepositoryItem("33b1d8ea-62cc-43aa-9f41-61f6183242a8")]
            public virtual Ranorex.PTag lbl_VaciarPapelera
            {
                get
                {
                    return _lbl_vaciarpapeleraInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The lbl_VaciarPapelera item info.
            /// </summary>
            [RepositoryItemInfo("33b1d8ea-62cc-43aa-9f41-61f6183242a8")]
            public virtual RepoItemInfo lbl_VaciarPapeleraInfo
            {
                get
                {
                    return _lbl_vaciarpapeleraInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("caa45446-3d79-4801-ad33-1a66433276b1")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("caa45446-3d79-4801-ad33-1a66433276b1")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MeControlSignoutLink item.
            /// </summary>
            [RepositoryItem("7a3d0984-c2aa-45bd-b98b-93d9f6e68a44")]
            public virtual Ranorex.ATag MeControlSignoutLink
            {
                get
                {
                    return _mecontrolsignoutlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MeControlSignoutLink item info.
            /// </summary>
            [RepositoryItemInfo("7a3d0984-c2aa-45bd-b98b-93d9f6e68a44")]
            public virtual RepoItemInfo MeControlSignoutLinkInfo
            {
                get
                {
                    return _mecontrolsignoutlinkInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag folder.
            /// </summary>
            [RepositoryFolder("08c9edc3-dbe1-4f41-b104-4a27d90fe32e")]
            public virtual PruebaOneDriveRepositoryFolders.SomeDivTagFolder SomeDivTag
            {
                get { return _somedivtag; }
            }

            /// <summary>
            /// The AppRoot folder.
            /// </summary>
            [RepositoryFolder("be81b796-01c0-4a43-bb97-2bf8e2678751")]
            public virtual PruebaOneDriveRepositoryFolders.AppRootFolder AppRoot
            {
                get { return _approot; }
            }

            /// <summary>
            /// The OdBasePageOdBasePageLeftNavVisibleO folder.
            /// </summary>
            [RepositoryFolder("e6b6a1d9-025c-4127-8c95-7ff39781b899")]
            public virtual PruebaOneDriveRepositoryFolders.OdBasePageOdBasePageLeftNavVisibleOFolder OdBasePageOdBasePageLeftNavVisibleO
            {
                get { return _odbasepageodbasepageleftnavvisibleo; }
            }
        }

        /// <summary>
        /// The SomeDivTagFolder folder.
        /// </summary>
        [RepositoryFolder("08c9edc3-dbe1-4f41-b104-4a27d90fe32e")]
        public partial class SomeDivTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new SomeDivTag  folder.
            /// </summary>
            public SomeDivTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeDivTag", ".//section[#'mainContent']/iframe[@src='https://odc.officeapps.live.com/odc/v2.0/hrd?rs=en-us&Ver=16&app=23&p=6&hm=0']/body/div[2]/?/?/main/div[2]", parentFolder, 30000, null, false, "08c9edc3-dbe1-4f41-b104-4a27d90fe32e", "")
            {
                _emailInfo = new RepoItemInfo(this, "Email", "div[2]/?/?/input[@type='email']", 30000, null, "9debdfd6-66bf-4db0-85e0-49ff0dab974a");
                _submitInfo = new RepoItemInfo(this, "Submit", "div[4]/input[@type='submit']", 30000, null, "b210198d-4f33-41c9-92c3-da44955fce2e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("08c9edc3-dbe1-4f41-b104-4a27d90fe32e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("08c9edc3-dbe1-4f41-b104-4a27d90fe32e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("9debdfd6-66bf-4db0-85e0-49ff0dab974a")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("9debdfd6-66bf-4db0-85e0-49ff0dab974a")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("b210198d-4f33-41c9-92c3-da44955fce2e")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("b210198d-4f33-41c9-92c3-da44955fce2e")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

        /// <summary>
        /// The AppRootFolder folder.
        /// </summary>
        [RepositoryFolder("be81b796-01c0-4a43-bb97-2bf8e2678751")]
        public partial class AppRootFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pruebawebinearInfo;
            RepoItemInfo _cargarInfo;
            RepoItemInfo _pruebawebtxtInfo;
            RepoItemInfo _misarchivosInfo;
            RepoItemInfo _rdo_selectfolderInfo;
            RepoItemInfo _carpetacreadaInfo;
            RepoItemInfo _eliminarInfo;
            RepoItemInfo _btn_papeleradereciclajeInfo;
            RepoItemInfo _lbl_papeleradereciclajeInfo;
            RepoItemInfo _vaciarpapeleradereciclajeInfo;
            RepoItemInfo _spantagsiInfo;
            RepoItemInfo _lapapeleradereciclajeestavaciaInfo;

            /// <summary>
            /// Creates a new AppRoot  folder.
            /// </summary>
            public AppRootFolder(RepoGenBaseFolder parentFolder) :
                    base("AppRoot", ".//div[#'appRoot']", parentFolder, 30000, null, false, "be81b796-01c0-4a43-bb97-2bf8e2678751", "")
            {
                _pruebawebinearInfo = new RepoItemInfo(this, "PruebaWebinear", ".//main//nav/ul//span[@title='PruebaWebinear']", 30000, null, "f6757d9d-0d11-4c8b-9bb3-734802a8d8c7");
                _cargarInfo = new RepoItemInfo(this, "Cargar", ".//button[@title>'Cargar archivos de tu equipo']//span[@innertext='Cargar']", 30000, null, "24529e33-4d2f-475f-8379-2f21fa1f0fa8");
                _pruebawebtxtInfo = new RepoItemInfo(this, "PruebaWebTxt", ".//main//a[@href>'https://onedrive.live.com']//span[@innertext='pruebaWeb.txt']", 30000, null, "d41c017c-205d-4c13-a69b-62e0fc0ee946");
                _misarchivosInfo = new RepoItemInfo(this, "MisArchivos", "div/div[2]/div[4]/nav/div/div[1]/div/div/div/div/div[2]/div/a[1]/?/?/span[@title='Mis archivos']", 30000, null, "d194ab17-26a9-4e05-a6b6-fba07dbc17fb");
                _rdo_selectfolderInfo = new RepoItemInfo(this, "rdo_SelectFolder", ".//div[@data-automationid='PruebaWebinear']/span//i[@innertext='']", 30000, null, "76343086-b6c0-44f6-8cdb-b525c0798e7e");
                _carpetacreadaInfo = new RepoItemInfo(this, "CarpetaCreada", ".//div[@data-automationid='PruebaWebinear']", 30000, null, "2e885f9a-48a1-4fe1-861f-857d919fa0a0");
                _eliminarInfo = new RepoItemInfo(this, "Eliminar", ".//button[@title='Eliminar']//span[@innertext='Eliminar']", 30000, null, "17e5b949-17d0-41a6-abd3-7397d4db0470");
                _btn_papeleradereciclajeInfo = new RepoItemInfo(this, "btn_PapeleraDeReciclaje", ".//nav//span[@title='Papelera de reciclaje']", 30000, null, "2a304d2c-b8dd-46d4-9508-e3c51714a8d8");
                _lbl_papeleradereciclajeInfo = new RepoItemInfo(this, "lbl_PapeleraDeReciclaje", ".//main//h1[@innertext='Papelera de reciclaje']", 30000, null, "d7c397e5-cdd9-493c-9304-e0e631b3eaa7");
                _vaciarpapeleradereciclajeInfo = new RepoItemInfo(this, "VaciarPapeleraDeReciclaje", ".//button[@title>'Vaciar papelera de recicl']//span[@innertext>'Vaciar papelera de recicl']", 30000, null, "bbafddfb-93e3-4ff0-a657-3c3c5921f21c");
                _spantagsiInfo = new RepoItemInfo(this, "SpanTagSi", ".//span[@innertext='Sí']", 30000, null, "4e8b6282-75c9-498f-bc09-0d84414c76c1");
                _lapapeleradereciclajeestavaciaInfo = new RepoItemInfo(this, "LaPapeleraDeReciclajeEstaVacia", ".//main///div[@innertext='La papelera de reciclaje está vacía']", 30000, null, "c5f478cc-17b3-4d01-a935-c0d9c98055cb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be81b796-01c0-4a43-bb97-2bf8e2678751")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be81b796-01c0-4a43-bb97-2bf8e2678751")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PruebaWebinear item.
            /// </summary>
            [RepositoryItem("f6757d9d-0d11-4c8b-9bb3-734802a8d8c7")]
            public virtual Ranorex.SpanTag PruebaWebinear
            {
                get
                {
                    return _pruebawebinearInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PruebaWebinear item info.
            /// </summary>
            [RepositoryItemInfo("f6757d9d-0d11-4c8b-9bb3-734802a8d8c7")]
            public virtual RepoItemInfo PruebaWebinearInfo
            {
                get
                {
                    return _pruebawebinearInfo;
                }
            }

            /// <summary>
            /// The Cargar item.
            /// </summary>
            [RepositoryItem("24529e33-4d2f-475f-8379-2f21fa1f0fa8")]
            public virtual Ranorex.SpanTag Cargar
            {
                get
                {
                    return _cargarInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Cargar item info.
            /// </summary>
            [RepositoryItemInfo("24529e33-4d2f-475f-8379-2f21fa1f0fa8")]
            public virtual RepoItemInfo CargarInfo
            {
                get
                {
                    return _cargarInfo;
                }
            }

            /// <summary>
            /// The PruebaWebTxt item.
            /// </summary>
            [RepositoryItem("d41c017c-205d-4c13-a69b-62e0fc0ee946")]
            public virtual Ranorex.SpanTag PruebaWebTxt
            {
                get
                {
                    return _pruebawebtxtInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PruebaWebTxt item info.
            /// </summary>
            [RepositoryItemInfo("d41c017c-205d-4c13-a69b-62e0fc0ee946")]
            public virtual RepoItemInfo PruebaWebTxtInfo
            {
                get
                {
                    return _pruebawebtxtInfo;
                }
            }

            /// <summary>
            /// The MisArchivos item.
            /// </summary>
            [RepositoryItem("d194ab17-26a9-4e05-a6b6-fba07dbc17fb")]
            public virtual Ranorex.SpanTag MisArchivos
            {
                get
                {
                    return _misarchivosInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MisArchivos item info.
            /// </summary>
            [RepositoryItemInfo("d194ab17-26a9-4e05-a6b6-fba07dbc17fb")]
            public virtual RepoItemInfo MisArchivosInfo
            {
                get
                {
                    return _misarchivosInfo;
                }
            }

            /// <summary>
            /// The rdo_SelectFolder item.
            /// </summary>
            [RepositoryItem("76343086-b6c0-44f6-8cdb-b525c0798e7e")]
            public virtual Ranorex.ITag rdo_SelectFolder
            {
                get
                {
                    return _rdo_selectfolderInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The rdo_SelectFolder item info.
            /// </summary>
            [RepositoryItemInfo("76343086-b6c0-44f6-8cdb-b525c0798e7e")]
            public virtual RepoItemInfo rdo_SelectFolderInfo
            {
                get
                {
                    return _rdo_selectfolderInfo;
                }
            }

            /// <summary>
            /// The CarpetaCreada item.
            /// </summary>
            [RepositoryItem("2e885f9a-48a1-4fe1-861f-857d919fa0a0")]
            public virtual Ranorex.DivTag CarpetaCreada
            {
                get
                {
                    return _carpetacreadaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CarpetaCreada item info.
            /// </summary>
            [RepositoryItemInfo("2e885f9a-48a1-4fe1-861f-857d919fa0a0")]
            public virtual RepoItemInfo CarpetaCreadaInfo
            {
                get
                {
                    return _carpetacreadaInfo;
                }
            }

            /// <summary>
            /// The Eliminar item.
            /// </summary>
            [RepositoryItem("17e5b949-17d0-41a6-abd3-7397d4db0470")]
            public virtual Ranorex.SpanTag Eliminar
            {
                get
                {
                    return _eliminarInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Eliminar item info.
            /// </summary>
            [RepositoryItemInfo("17e5b949-17d0-41a6-abd3-7397d4db0470")]
            public virtual RepoItemInfo EliminarInfo
            {
                get
                {
                    return _eliminarInfo;
                }
            }

            /// <summary>
            /// The btn_PapeleraDeReciclaje item.
            /// </summary>
            [RepositoryItem("2a304d2c-b8dd-46d4-9508-e3c51714a8d8")]
            public virtual Ranorex.SpanTag btn_PapeleraDeReciclaje
            {
                get
                {
                    return _btn_papeleradereciclajeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The btn_PapeleraDeReciclaje item info.
            /// </summary>
            [RepositoryItemInfo("2a304d2c-b8dd-46d4-9508-e3c51714a8d8")]
            public virtual RepoItemInfo btn_PapeleraDeReciclajeInfo
            {
                get
                {
                    return _btn_papeleradereciclajeInfo;
                }
            }

            /// <summary>
            /// The lbl_PapeleraDeReciclaje item.
            /// </summary>
            [RepositoryItem("d7c397e5-cdd9-493c-9304-e0e631b3eaa7")]
            public virtual Ranorex.H1Tag lbl_PapeleraDeReciclaje
            {
                get
                {
                    return _lbl_papeleradereciclajeInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The lbl_PapeleraDeReciclaje item info.
            /// </summary>
            [RepositoryItemInfo("d7c397e5-cdd9-493c-9304-e0e631b3eaa7")]
            public virtual RepoItemInfo lbl_PapeleraDeReciclajeInfo
            {
                get
                {
                    return _lbl_papeleradereciclajeInfo;
                }
            }

            /// <summary>
            /// The VaciarPapeleraDeReciclaje item.
            /// </summary>
            [RepositoryItem("bbafddfb-93e3-4ff0-a657-3c3c5921f21c")]
            public virtual Ranorex.SpanTag VaciarPapeleraDeReciclaje
            {
                get
                {
                    return _vaciarpapeleradereciclajeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The VaciarPapeleraDeReciclaje item info.
            /// </summary>
            [RepositoryItemInfo("bbafddfb-93e3-4ff0-a657-3c3c5921f21c")]
            public virtual RepoItemInfo VaciarPapeleraDeReciclajeInfo
            {
                get
                {
                    return _vaciarpapeleradereciclajeInfo;
                }
            }

            /// <summary>
            /// The SpanTagSi item.
            /// </summary>
            [RepositoryItem("4e8b6282-75c9-498f-bc09-0d84414c76c1")]
            public virtual Ranorex.SpanTag SpanTagSi
            {
                get
                {
                    return _spantagsiInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagSi item info.
            /// </summary>
            [RepositoryItemInfo("4e8b6282-75c9-498f-bc09-0d84414c76c1")]
            public virtual RepoItemInfo SpanTagSiInfo
            {
                get
                {
                    return _spantagsiInfo;
                }
            }

            /// <summary>
            /// The LaPapeleraDeReciclajeEstaVacia item.
            /// </summary>
            [RepositoryItem("c5f478cc-17b3-4d01-a935-c0d9c98055cb")]
            public virtual Ranorex.DivTag LaPapeleraDeReciclajeEstaVacia
            {
                get
                {
                    return _lapapeleradereciclajeestavaciaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LaPapeleraDeReciclajeEstaVacia item info.
            /// </summary>
            [RepositoryItemInfo("c5f478cc-17b3-4d01-a935-c0d9c98055cb")]
            public virtual RepoItemInfo LaPapeleraDeReciclajeEstaVaciaInfo
            {
                get
                {
                    return _lapapeleradereciclajeestavaciaInfo;
                }
            }
        }

        /// <summary>
        /// The OdBasePageOdBasePageLeftNavVisibleOFolder folder.
        /// </summary>
        [RepositoryFolder("e6b6a1d9-025c-4127-8c95-7ff39781b899")]
        public partial class OdBasePageOdBasePageLeftNavVisibleOFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nuevoInfo;
            RepoItemInfo _pruebawebinearInfo;
            RepoItemInfo _crearInfo;
            RepoItemInfo _imgtagfInfo;

            /// <summary>
            /// Creates a new OdBasePageOdBasePageLeftNavVisibleO  folder.
            /// </summary>
            public OdBasePageOdBasePageLeftNavVisibleOFolder(RepoGenBaseFolder parentFolder) :
                    base("OdBasePageOdBasePageLeftNavVisibleO", ".//div[#'appRoot']//div[@id='appRoot']", parentFolder, 30000, null, false, "e6b6a1d9-025c-4127-8c95-7ff39781b899", "")
            {
                _nuevoInfo = new RepoItemInfo(this, "Nuevo", ".//button[@title>'Crear una carpeta o un documento']//span[@innertext='Nuevo']", 30000, null, "94f3a55f-019e-4572-82ef-d28e564bf98c");
                _pruebawebinearInfo = new RepoItemInfo(this, "PruebaWebinear", ".///a[@href>'https://onedrive.live.com']//span[@innertext='PruebaWebinear']", 30000, null, "4849b1ac-37fd-4a63-8a7d-7c5ed4d95fc5");
                _crearInfo = new RepoItemInfo(this, "Crear", ".//span[@innertext='Crear']", 30000, null, "5e5d0407-c0df-48dd-9451-c43ab5becd3b");
                _imgtagfInfo = new RepoItemInfo(this, "ImgTagF", ".//img[@alt='F']", 30000, null, "0f7c9100-f046-4ddf-83b8-68cf391d40dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e6b6a1d9-025c-4127-8c95-7ff39781b899")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e6b6a1d9-025c-4127-8c95-7ff39781b899")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Nuevo item.
            /// </summary>
            [RepositoryItem("94f3a55f-019e-4572-82ef-d28e564bf98c")]
            public virtual Ranorex.SpanTag Nuevo
            {
                get
                {
                    return _nuevoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Nuevo item info.
            /// </summary>
            [RepositoryItemInfo("94f3a55f-019e-4572-82ef-d28e564bf98c")]
            public virtual RepoItemInfo NuevoInfo
            {
                get
                {
                    return _nuevoInfo;
                }
            }

            /// <summary>
            /// The PruebaWebinear item.
            /// </summary>
            [RepositoryItem("4849b1ac-37fd-4a63-8a7d-7c5ed4d95fc5")]
            public virtual Ranorex.SpanTag PruebaWebinear
            {
                get
                {
                    return _pruebawebinearInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PruebaWebinear item info.
            /// </summary>
            [RepositoryItemInfo("4849b1ac-37fd-4a63-8a7d-7c5ed4d95fc5")]
            public virtual RepoItemInfo PruebaWebinearInfo
            {
                get
                {
                    return _pruebawebinearInfo;
                }
            }

            /// <summary>
            /// The Crear item.
            /// </summary>
            [RepositoryItem("5e5d0407-c0df-48dd-9451-c43ab5becd3b")]
            public virtual Ranorex.SpanTag Crear
            {
                get
                {
                    return _crearInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Crear item info.
            /// </summary>
            [RepositoryItemInfo("5e5d0407-c0df-48dd-9451-c43ab5becd3b")]
            public virtual RepoItemInfo CrearInfo
            {
                get
                {
                    return _crearInfo;
                }
            }

            /// <summary>
            /// The ImgTagF item.
            /// </summary>
            [RepositoryItem("0f7c9100-f046-4ddf-83b8-68cf391d40dc")]
            public virtual Ranorex.ImgTag ImgTagF
            {
                get
                {
                    return _imgtagfInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgTagF item info.
            /// </summary>
            [RepositoryItemInfo("0f7c9100-f046-4ddf-83b8-68cf391d40dc")]
            public virtual RepoItemInfo ImgTagFInfo
            {
                get
                {
                    return _imgtagfInfo;
                }
            }
        }

        /// <summary>
        /// The SignInMicrosoftOneDriver_COFAppFolder folder.
        /// </summary>
        [RepositoryFolder("d4f4bec1-a29a-4b36-add8-c4c886887ff9")]
        public partial class SignInMicrosoftOneDriver_COFAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _personalaccountInfo;
            RepoItemInfo _copy_of_carpetacreadaInfo;
            RepoItemInfo _copy_of_pruebawebinearInfo;
            RepoItemInfo _copy_of_pruebawebtxtInfo;

            /// <summary>
            /// Creates a new SignInMicrosoftOneDriver_COF  folder.
            /// </summary>
            public SignInMicrosoftOneDriver_COFAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInMicrosoftOneDriver_COF", "/dom[@domain~'live.com']", parentFolder, 5000, null, false, "d4f4bec1-a29a-4b36-add8-c4c886887ff9", "")
            {
                _personalaccountInfo = new RepoItemInfo(this, "PersonalAccount", ".//section[#'mainContent']/iframe[@src='https://odc.officeapps.live.com/odc/v2.0/hrd?rs=en-us&Ver=16&app=23&p=6&hm=0']/body/div[2]/?/?/main/div[2]/div[3]/?/?/div[@innertext='Personal account']", 0, null, "5517c35e-884a-4e60-93c8-3984b8393d02");
                _copy_of_carpetacreadaInfo = new RepoItemInfo(this, "Copy_of_CarpetaCreada", ".//div[@data-automationid='PruebaWebinear']", 0, null, "58b059d4-4416-4f16-ac8f-927e2734b80e");
                _copy_of_pruebawebinearInfo = new RepoItemInfo(this, "Copy_of_PruebaWebinear", ".//div[#'appRoot']//div[@id='appRoot']///a[@href>'https://onedrive.live.com']//span[@innertext='PruebaWebinear']", 0, null, "09daedd1-42c6-4eb7-92cb-51317bda0488");
                _copy_of_pruebawebtxtInfo = new RepoItemInfo(this, "Copy_of_PruebaWebTxt", ".//div[#'appRoot']//main//a[@href>'https://onedrive.live.com']//span[@innertext='pruebaWeb.txt']", 0, null, "ce4fe7dd-2dd5-4b24-b4c1-83c8e36b5298");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d4f4bec1-a29a-4b36-add8-c4c886887ff9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4f4bec1-a29a-4b36-add8-c4c886887ff9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PersonalAccount item.
            /// </summary>
            [RepositoryItem("5517c35e-884a-4e60-93c8-3984b8393d02")]
            public virtual Ranorex.DivTag PersonalAccount
            {
                get
                {
                    return _personalaccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalAccount item info.
            /// </summary>
            [RepositoryItemInfo("5517c35e-884a-4e60-93c8-3984b8393d02")]
            public virtual RepoItemInfo PersonalAccountInfo
            {
                get
                {
                    return _personalaccountInfo;
                }
            }

            /// <summary>
            /// The Copy_of_CarpetaCreada item.
            /// </summary>
            [RepositoryItem("58b059d4-4416-4f16-ac8f-927e2734b80e")]
            public virtual Ranorex.DivTag Copy_of_CarpetaCreada
            {
                get
                {
                    return _copy_of_carpetacreadaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_CarpetaCreada item info.
            /// </summary>
            [RepositoryItemInfo("58b059d4-4416-4f16-ac8f-927e2734b80e")]
            public virtual RepoItemInfo Copy_of_CarpetaCreadaInfo
            {
                get
                {
                    return _copy_of_carpetacreadaInfo;
                }
            }

            /// <summary>
            /// The Copy_of_PruebaWebinear item.
            /// </summary>
            [RepositoryItem("09daedd1-42c6-4eb7-92cb-51317bda0488")]
            public virtual Ranorex.SpanTag Copy_of_PruebaWebinear
            {
                get
                {
                    return _copy_of_pruebawebinearInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_PruebaWebinear item info.
            /// </summary>
            [RepositoryItemInfo("09daedd1-42c6-4eb7-92cb-51317bda0488")]
            public virtual RepoItemInfo Copy_of_PruebaWebinearInfo
            {
                get
                {
                    return _copy_of_pruebawebinearInfo;
                }
            }

            /// <summary>
            /// The Copy_of_PruebaWebTxt item.
            /// </summary>
            [RepositoryItem("ce4fe7dd-2dd5-4b24-b4c1-83c8e36b5298")]
            public virtual Ranorex.SpanTag Copy_of_PruebaWebTxt
            {
                get
                {
                    return _copy_of_pruebawebtxtInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_PruebaWebTxt item info.
            /// </summary>
            [RepositoryItemInfo("ce4fe7dd-2dd5-4b24-b4c1-83c8e36b5298")]
            public virtual RepoItemInfo Copy_of_PruebaWebTxtInfo
            {
                get
                {
                    return _copy_of_pruebawebtxtInfo;
                }
            }
        }

        /// <summary>
        /// The PersonalCloudStorageMicrosoftOneDriAppFolder folder.
        /// </summary>
        [RepositoryFolder("71c3c745-a87c-4440-a406-daa0e93fa6f5")]
        public partial class PersonalCloudStorageMicrosoftOneDriAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpsgomicrosoftcomfwlinkplinkidInfo;

            /// <summary>
            /// Creates a new PersonalCloudStorageMicrosoftOneDri  folder.
            /// </summary>
            public PersonalCloudStorageMicrosoftOneDriAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PersonalCloudStorageMicrosoftOneDri", "/dom[@domain='www.microsoft.com']", parentFolder, 30000, null, false, "71c3c745-a87c-4440-a406-daa0e93fa6f5", "")
            {
                _httpsgomicrosoftcomfwlinkplinkidInfo = new RepoItemInfo(this, "HttpsGoMicrosoftComFwlinkPLinkID", ".//div[#'heroregion']/?/?/section/div/div/div/div/div/div/div[1]/a[@href>'https://go.microsoft.com/']", 30000, null, "84324fc2-b0ca-4b88-8b86-807fea3a1487");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71c3c745-a87c-4440-a406-daa0e93fa6f5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71c3c745-a87c-4440-a406-daa0e93fa6f5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsGoMicrosoftComFwlinkPLinkID item.
            /// </summary>
            [RepositoryItem("84324fc2-b0ca-4b88-8b86-807fea3a1487")]
            public virtual Ranorex.ATag HttpsGoMicrosoftComFwlinkPLinkID
            {
                get
                {
                    return _httpsgomicrosoftcomfwlinkplinkidInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsGoMicrosoftComFwlinkPLinkID item info.
            /// </summary>
            [RepositoryItemInfo("84324fc2-b0ca-4b88-8b86-807fea3a1487")]
            public virtual RepoItemInfo HttpsGoMicrosoftComFwlinkPLinkIDInfo
            {
                get
                {
                    return _httpsgomicrosoftcomfwlinkplinkidInfo;
                }
            }
        }

        /// <summary>
        /// The AbrirAppFolder folder.
        /// </summary>
        [RepositoryFolder("1362989b-eaf3-4e1f-9238-2790078eaa5c")]
        public partial class AbrirAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _escritorioInfo;
            RepoItemInfo _text1148Info;
            RepoItemInfo _buttonabrirInfo;

            /// <summary>
            /// Creates a new Abrir  folder.
            /// </summary>
            public AbrirAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Abrir", "/form[@title='Abrir']", parentFolder, 30000, null, true, "1362989b-eaf3-4e1f-9238-2790078eaa5c", "")
            {
                _escritorioInfo = new RepoItemInfo(this, "Escritorio", "element[@class='WorkerW']/container[@controlid='40965']//toolbar[@controlid='1001']/button[@text='Escritorio']", 30000, null, "c952640b-4d34-4bc1-b9bf-7e9b1d610280");
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", 30000, null, "d6513251-e68e-47f4-ae1f-53a3ada7871e");
                _buttonabrirInfo = new RepoItemInfo(this, "ButtonAbrir", "button[@text='&Abrir']", 30000, null, "bde753be-6f85-4df1-8ac7-115715604dcf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1362989b-eaf3-4e1f-9238-2790078eaa5c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1362989b-eaf3-4e1f-9238-2790078eaa5c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Escritorio item.
            /// </summary>
            [RepositoryItem("c952640b-4d34-4bc1-b9bf-7e9b1d610280")]
            public virtual Ranorex.Button Escritorio
            {
                get
                {
                    return _escritorioInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Escritorio item info.
            /// </summary>
            [RepositoryItemInfo("c952640b-4d34-4bc1-b9bf-7e9b1d610280")]
            public virtual RepoItemInfo EscritorioInfo
            {
                get
                {
                    return _escritorioInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("d6513251-e68e-47f4-ae1f-53a3ada7871e")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("d6513251-e68e-47f4-ae1f-53a3ada7871e")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The ButtonAbrir item.
            /// </summary>
            [RepositoryItem("bde753be-6f85-4df1-8ac7-115715604dcf")]
            public virtual Ranorex.Button ButtonAbrir
            {
                get
                {
                    return _buttonabrirInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAbrir item info.
            /// </summary>
            [RepositoryItemInfo("bde753be-6f85-4df1-8ac7-115715604dcf")]
            public virtual RepoItemInfo ButtonAbrirInfo
            {
                get
                {
                    return _buttonabrirInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
