///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DemoWeb
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemoWebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("480b6d1f-38df-4e50-9052-80754d92f698")]
    public partial class DemoWebRepository : RepoGenBaseFolder
    {
        static DemoWebRepository instance = new DemoWebRepository();
        DemoWebRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        DemoWebRepositoryFolders.OneDriveAppFolder _onedrive;
        DemoWebRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder _personalcloudstoragemicrosoftonedri;

        /// <summary>
        /// Gets the singleton class instance representing the DemoWebRepository element repository.
        /// </summary>
        [RepositoryFolder("480b6d1f-38df-4e50-9052-80754d92f698")]
        public static DemoWebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemoWebRepository() 
            : base("DemoWebRepository", "/", null, 0, false, "480b6d1f-38df-4e50-9052-80754d92f698", ".\\RepositoryImages\\DemoWebRepository480b6d1f.rximgres")
        {
            _applicationundertest = new DemoWebRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _onedrive = new DemoWebRepositoryFolders.OneDriveAppFolder(this);
            _personalcloudstoragemicrosoftonedri = new DemoWebRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("480b6d1f-38df-4e50-9052-80754d92f698")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a2c89581-3502-484d-b25d-24f2bb1a5914")]
        public virtual DemoWebRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The OneDrive folder.
        /// </summary>
        [RepositoryFolder("47fb193a-2e02-4088-a2b5-1390f0234c28")]
        public virtual DemoWebRepositoryFolders.OneDriveAppFolder OneDrive
        {
            get { return _onedrive; }
        }

        /// <summary>
        /// The PersonalCloudStorageMicrosoftOneDri folder.
        /// </summary>
        [RepositoryFolder("e17f31a9-8dbd-4029-8062-f21f23fd9b91")]
        public virtual DemoWebRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder PersonalCloudStorageMicrosoftOneDri
        {
            get { return _personalcloudstoragemicrosoftonedri; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DemoWebRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a2c89581-3502-484d-b25d-24f2bb1a5914")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            DemoWebRepositoryFolders.OuterFolder _outer;
            RepoItemInfo _httpsspoprodaakamaihdnetfilesfabInfo;
            RepoItemInfo _imgtagfInfo;
            RepoItemInfo _mecontrolsignoutlinkInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='onedrive.live.com']", parentFolder, 30000, null, false, "a2c89581-3502-484d-b25d-24f2bb1a5914", "")
            {
                _outer = new DemoWebRepositoryFolders.OuterFolder(this);
                _httpsspoprodaakamaihdnetfilesfabInfo = new RepoItemInfo(this, "HttpsSpoprodAAkamaihdNetFilesFab", ".//div[#'appRoot']/div/div[2]/div[5]/main/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div/div[1]/div/div/div/a[@href>'https://onedrive.live.com']/span[2]/span/span//img[@src='https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-react-assets/foldericons/vault-lg.svg']", 30000, null, "8eb5d080-f163-4538-ba01-c09115fe8e46");
                _imgtagfInfo = new RepoItemInfo(this, "ImgTagF", ".//div[#'appRoot']/div/div[1]/div/div[1]/div[3]/div[1]/button[@title>'Administrador de cuenta para']/div/div[2]//img[@alt='F']", 30000, null, "dc929210-adb9-4cfb-8f12-80ee8e762585");
                _mecontrolsignoutlinkInfo = new RepoItemInfo(this, "MeControlSignoutLink", ".//a[#'meControlSignoutLink']", 30000, null, "55f5866d-87ec-407c-b3f7-7f14621b93b0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a2c89581-3502-484d-b25d-24f2bb1a5914")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a2c89581-3502-484d-b25d-24f2bb1a5914")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsSpoprodAAkamaihdNetFilesFab item.
            /// </summary>
            [RepositoryItem("8eb5d080-f163-4538-ba01-c09115fe8e46")]
            public virtual Ranorex.ImgTag HttpsSpoprodAAkamaihdNetFilesFab
            {
                get
                {
                    return _httpsspoprodaakamaihdnetfilesfabInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsSpoprodAAkamaihdNetFilesFab item info.
            /// </summary>
            [RepositoryItemInfo("8eb5d080-f163-4538-ba01-c09115fe8e46")]
            public virtual RepoItemInfo HttpsSpoprodAAkamaihdNetFilesFabInfo
            {
                get
                {
                    return _httpsspoprodaakamaihdnetfilesfabInfo;
                }
            }

            /// <summary>
            /// The ImgTagF item.
            /// </summary>
            [RepositoryItem("dc929210-adb9-4cfb-8f12-80ee8e762585")]
            public virtual Ranorex.ImgTag ImgTagF
            {
                get
                {
                    return _imgtagfInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgTagF item info.
            /// </summary>
            [RepositoryItemInfo("dc929210-adb9-4cfb-8f12-80ee8e762585")]
            public virtual RepoItemInfo ImgTagFInfo
            {
                get
                {
                    return _imgtagfInfo;
                }
            }

            /// <summary>
            /// The MeControlSignoutLink item.
            /// </summary>
            [RepositoryItem("55f5866d-87ec-407c-b3f7-7f14621b93b0")]
            public virtual Ranorex.ATag MeControlSignoutLink
            {
                get
                {
                    return _mecontrolsignoutlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MeControlSignoutLink item info.
            /// </summary>
            [RepositoryItemInfo("55f5866d-87ec-407c-b3f7-7f14621b93b0")]
            public virtual RepoItemInfo MeControlSignoutLinkInfo
            {
                get
                {
                    return _mecontrolsignoutlinkInfo;
                }
            }

            /// <summary>
            /// The Outer folder.
            /// </summary>
            [RepositoryFolder("bb086b8c-e23a-492c-b742-2da6d2a8ac9a")]
            public virtual DemoWebRepositoryFolders.OuterFolder Outer
            {
                get { return _outer; }
            }
        }

        /// <summary>
        /// The OuterFolder folder.
        /// </summary>
        [RepositoryFolder("bb086b8c-e23a-492c-b742-2da6d2a8ac9a")]
        public partial class OuterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _signinInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _personalaccountInfo;

            /// <summary>
            /// Creates a new Outer  folder.
            /// </summary>
            public OuterFolder(RepoGenBaseFolder parentFolder) :
                    base("Outer", ".//section[#'mainContent']/iframe[@src='https://odc.officeapps.live.com/odc/v2.0/hrd?rs=en-us&Ver=16&app=23&p=6&hm=0']/body/div[2]", parentFolder, 30000, null, false, "bb086b8c-e23a-492c-b742-2da6d2a8ac9a", "")
            {
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//h1[@innertext='Sign in']", 30000, null, "d97a176a-1024-4b50-8188-7e0373b154c8");
                _emailInfo = new RepoItemInfo(this, "Email", "?/?/main/div[2]/div[2]/?/?/input[@type='email']", 30000, null, "6014a13f-f9f5-4ad9-bdd3-4fa1504d1651");
                _submitInfo = new RepoItemInfo(this, "Submit", "?/?/main/div[2]/div[4]/input[@type='submit']", 30000, null, "deaadca1-b920-4a75-8def-caea1921ecec");
                _personalaccountInfo = new RepoItemInfo(this, "PersonalAccount", "?/?/main/div[2]/div[3]/?/?/div[@innertext='Personal account']", 30000, null, "4e73e5e7-e84f-4bb5-85ad-5d7291f5f914");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bb086b8c-e23a-492c-b742-2da6d2a8ac9a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bb086b8c-e23a-492c-b742-2da6d2a8ac9a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("d97a176a-1024-4b50-8188-7e0373b154c8")]
            public virtual Ranorex.H1Tag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("d97a176a-1024-4b50-8188-7e0373b154c8")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("6014a13f-f9f5-4ad9-bdd3-4fa1504d1651")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("6014a13f-f9f5-4ad9-bdd3-4fa1504d1651")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("deaadca1-b920-4a75-8def-caea1921ecec")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("deaadca1-b920-4a75-8def-caea1921ecec")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The PersonalAccount item.
            /// </summary>
            [RepositoryItem("4e73e5e7-e84f-4bb5-85ad-5d7291f5f914")]
            public virtual Ranorex.DivTag PersonalAccount
            {
                get
                {
                    return _personalaccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalAccount item info.
            /// </summary>
            [RepositoryItemInfo("4e73e5e7-e84f-4bb5-85ad-5d7291f5f914")]
            public virtual RepoItemInfo PersonalAccountInfo
            {
                get
                {
                    return _personalaccountInfo;
                }
            }
        }

        /// <summary>
        /// The OneDriveAppFolder folder.
        /// </summary>
        [RepositoryFolder("47fb193a-2e02-4088-a2b5-1390f0234c28")]
        public partial class OneDriveAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwdInfo;
            RepoItemInfo _idsibutton9Info;

            /// <summary>
            /// Creates a new OneDrive  folder.
            /// </summary>
            public OneDriveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OneDrive", "/dom[@domain='login.live.com']", parentFolder, 30000, null, false, "47fb193a-2e02-4088-a2b5-1390f0234c28", "")
            {
                _passwdInfo = new RepoItemInfo(this, "Passwd", "body/?/?/form[@name='f1']/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div[2]//input[@name='passwd']", 30000, null, "382926de-c6f9-46ec-b133-3bb9d0e5965d");
                _idsibutton9Info = new RepoItemInfo(this, "IdSIButton9", ".//input[#'idSIButton9']", 30000, null, "67116216-594f-49c3-adba-6b0071037248");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("47fb193a-2e02-4088-a2b5-1390f0234c28")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("47fb193a-2e02-4088-a2b5-1390f0234c28")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Passwd item.
            /// </summary>
            [RepositoryItem("382926de-c6f9-46ec-b133-3bb9d0e5965d")]
            public virtual Ranorex.InputTag Passwd
            {
                get
                {
                    return _passwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Passwd item info.
            /// </summary>
            [RepositoryItemInfo("382926de-c6f9-46ec-b133-3bb9d0e5965d")]
            public virtual RepoItemInfo PasswdInfo
            {
                get
                {
                    return _passwdInfo;
                }
            }

            /// <summary>
            /// The IdSIButton9 item.
            /// </summary>
            [RepositoryItem("67116216-594f-49c3-adba-6b0071037248")]
            public virtual Ranorex.InputTag IdSIButton9
            {
                get
                {
                    return _idsibutton9Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IdSIButton9 item info.
            /// </summary>
            [RepositoryItemInfo("67116216-594f-49c3-adba-6b0071037248")]
            public virtual RepoItemInfo IdSIButton9Info
            {
                get
                {
                    return _idsibutton9Info;
                }
            }
        }

        /// <summary>
        /// The PersonalCloudStorageMicrosoftOneDriAppFolder folder.
        /// </summary>
        [RepositoryFolder("e17f31a9-8dbd-4029-8062-f21f23fd9b91")]
        public partial class PersonalCloudStorageMicrosoftOneDriAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _onedriveInfo;

            /// <summary>
            /// Creates a new PersonalCloudStorageMicrosoftOneDri  folder.
            /// </summary>
            public PersonalCloudStorageMicrosoftOneDriAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PersonalCloudStorageMicrosoftOneDri", "/dom[@domain='www.microsoft.com']", parentFolder, 30000, null, false, "e17f31a9-8dbd-4029-8062-f21f23fd9b91", "")
            {
                _onedriveInfo = new RepoItemInfo(this, "OneDrive", ".//div[#'heroregion']/div[1]/section/div/div[1]//h1[@innertext='OneDrive']", 30000, null, "056c1494-a9e7-4057-b50d-c5a48e473473");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e17f31a9-8dbd-4029-8062-f21f23fd9b91")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e17f31a9-8dbd-4029-8062-f21f23fd9b91")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OneDrive item.
            /// </summary>
            [RepositoryItem("056c1494-a9e7-4057-b50d-c5a48e473473")]
            public virtual Ranorex.H1Tag OneDrive
            {
                get
                {
                    return _onedriveInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The OneDrive item info.
            /// </summary>
            [RepositoryItemInfo("056c1494-a9e7-4057-b50d-c5a48e473473")]
            public virtual RepoItemInfo OneDriveInfo
            {
                get
                {
                    return _onedriveInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
