///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoWeb
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("d7cc468f-7653-4ce5-863d-e1dc70e4123a", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoWebRepository repository.
        /// </summary>
        public static DemoWebRepository repo = DemoWebRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Outer.Email' at 90;15.", repo.ApplicationUnderTest.Outer.EmailInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Outer.Email.Click("90;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fernando_figliola@itrsa.com.ar' with focus on 'ApplicationUnderTest.Outer.Email'.", repo.ApplicationUnderTest.Outer.EmailInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Outer.Email.PressKeys("fernando_figliola@itrsa.com.ar");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Outer.Submit' at 42;14.", repo.ApplicationUnderTest.Outer.SubmitInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Outer.Submit.Click("42;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Outer.PersonalAccount' at 45;18.", repo.ApplicationUnderTest.Outer.PersonalAccountInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Outer.PersonalAccount.Click("45;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OneDrive.Passwd' at 73;18.", repo.OneDrive.PasswdInfo, new RecordItemIndex(4));
            repo.OneDrive.Passwd.Click("73;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '●●●●●●●●●' with focus on 'OneDrive.Passwd'.", repo.OneDrive.PasswdInfo, new RecordItemIndex(5));
            repo.OneDrive.Passwd.PressKeys("M3ng4n0s!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OneDrive.IdSIButton9' at 49;15.", repo.OneDrive.IdSIButton9Info, new RecordItemIndex(6));
            repo.OneDrive.IdSIButton9.Click("49;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.HttpsSpoprodAAkamaihdNetFilesFab'.", repo.ApplicationUnderTest.HttpsSpoprodAAkamaihdNetFilesFabInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsSpoprodAAkamaihdNetFilesFabInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-react-assets/foldericons/vault-lg.svg') on item 'ApplicationUnderTest.HttpsSpoprodAAkamaihdNetFilesFab'.", repo.ApplicationUnderTest.HttpsSpoprodAAkamaihdNetFilesFabInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsSpoprodAAkamaihdNetFilesFabInfo, "Src", "https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-react-assets/foldericons/vault-lg.svg");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
