///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PruebaOneDrive.Generales
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignIn recording.
    /// </summary>
    [TestModule("f73aa6d4-8d12-4806-9e87-0e9982970da7", ModuleType.Recording, 1)]
    public partial class SignIn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PruebaOneDrive.PruebaOneDriveRepository repository.
        /// </summary>
        public static global::PruebaOneDrive.PruebaOneDriveRepository repo = global::PruebaOneDrive.PruebaOneDriveRepository.Instance;

        static SignIn instance = new SignIn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignIn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignIn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.SomeDivTag.Email' at CenterLeft.", repo.SignInMicrosoftOneDrive.SomeDivTag.EmailInfo, new RecordItemIndex(0));
            repo.SignInMicrosoftOneDrive.SomeDivTag.Email.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fernando_figliola@itrsa.com.ar' with focus on 'SignInMicrosoftOneDrive.SomeDivTag.Email'.", repo.SignInMicrosoftOneDrive.SomeDivTag.EmailInfo, new RecordItemIndex(1));
            repo.SignInMicrosoftOneDrive.SomeDivTag.Email.PressKeys("fernando_figliola@itrsa.com.ar");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.SomeDivTag.Submit' at Center.", repo.SignInMicrosoftOneDrive.SomeDivTag.SubmitInfo, new RecordItemIndex(2));
            repo.SignInMicrosoftOneDrive.SomeDivTag.Submit.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'SignInMicrosoftOneDriver_COF.PersonalAccount' at 62;11.", repo.SignInMicrosoftOneDriver_COF.PersonalAccountInfo, new RecordItemIndex(3));
                repo.SignInMicrosoftOneDriver_COF.PersonalAccount.Click("62;11");
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.Passwd' at CenterLeft.", repo.SignInMicrosoftOneDrive.PasswdInfo, new RecordItemIndex(4));
            repo.SignInMicrosoftOneDrive.Passwd.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '●●●●●●●●●' with focus on 'SignInMicrosoftOneDrive.Passwd'.", repo.SignInMicrosoftOneDrive.PasswdInfo, new RecordItemIndex(5));
            repo.SignInMicrosoftOneDrive.Passwd.PressKeys("M3ng4n0_!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.btn_SignIn' at Center.", repo.SignInMicrosoftOneDrive.btn_SignInInfo, new RecordItemIndex(6));
            repo.SignInMicrosoftOneDrive.btn_SignIn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.AlmacenPersonal'", repo.SignInMicrosoftOneDrive.AlmacenPersonalInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.SignInMicrosoftOneDrive.AlmacenPersonalInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
