///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Mobile.Navegacion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Acciones recording.
    /// </summary>
    [TestModule("a904e81e-2d93-42f3-8524-5c90d17b5483", ModuleType.Recording, 1)]
    public partial class Acciones : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Mobile.MobileRepository repository.
        /// </summary>
        public static global::Mobile.MobileRepository repo = global::Mobile.MobileRepository.Instance;

        static Acciones instance = new Acciones();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Acciones()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Acciones Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Open' at Center", repo.ComAndroidKeepass.OpenInfo, new RecordItemIndex(0));
            repo.ComAndroidKeepass.Open.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ComAndroidKeepass.Password'", repo.ComAndroidKeepass.PasswordInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.ComAndroidKeepass.PasswordInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Password' at Center", repo.ComAndroidKeepass.PasswordInfo, new RecordItemIndex(2));
            repo.ComAndroidKeepass.Password.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'M3ng4n0!' on item 'ComAndroidKeepass.Password'.", repo.ComAndroidKeepass.PasswordInfo, new RecordItemIndex(3));
            repo.ComAndroidKeepass.Password.Element.SetAttributeValue("Text", "M3ng4n0!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.PassOk' at Center", repo.ComAndroidKeepass.PassOkInfo, new RecordItemIndex(4));
            repo.ComAndroidKeepass.PassOk.Touch();
            Delay.Milliseconds(500);
            
            // Seleccion de Email
            Report.Log(ReportLevel.Info, "Section", "Seleccion de Email", new RecordItemIndex(5));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComAndroidKeepass.Self, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ComAndroidKeepass.Content.Raiz'", repo.ComAndroidKeepass.Content.RaizInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.ComAndroidKeepass.Content.RaizInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Content.EMail' at Center", repo.ComAndroidKeepass.Content.EMailInfo, new RecordItemIndex(8));
            repo.ComAndroidKeepass.Content.EMail.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ComAndroidKeepass.Content.Icon'", repo.ComAndroidKeepass.Content.IconInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.ComAndroidKeepass.Content.IconInfo.WaitForExists(30000);
            
            // Alta Password del Mail
            Report.Log(ReportLevel.Info, "Section", "Alta Password del Mail", new RecordItemIndex(10));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComAndroidKeepass.Self, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Content.AddEntry' at Center", repo.ComAndroidKeepass.Content.AddEntryInfo, new RecordItemIndex(12));
            repo.ComAndroidKeepass.Content.AddEntry.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ComAndroidKeepass.Content1.IconButton'", repo.ComAndroidKeepass.Content1.IconButtonInfo, new ActionTimeout(30000), new RecordItemIndex(13));
            repo.ComAndroidKeepass.Content1.IconButtonInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Content1.EntryTitle' at Center", repo.ComAndroidKeepass.Content1.EntryTitleInfo, new RecordItemIndex(14));
            repo.ComAndroidKeepass.Content1.EntryTitle.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'ITR Mail' on item 'ComAndroidKeepass.Content1.EntryTitle'.", repo.ComAndroidKeepass.Content1.EntryTitleInfo, new RecordItemIndex(15));
            repo.ComAndroidKeepass.Content1.EntryTitle.Element.SetAttributeValue("Text", "ITR Mail");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Content1.EntryUserName' at Center", repo.ComAndroidKeepass.Content1.EntryUserNameInfo, new RecordItemIndex(16));
            repo.ComAndroidKeepass.Content1.EntryUserName.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'fernando_figliola@itrsa.com.ar' on item 'ComAndroidKeepass.Content1.EntryUserName'.", repo.ComAndroidKeepass.Content1.EntryUserNameInfo, new RecordItemIndex(17));
            repo.ComAndroidKeepass.Content1.EntryUserName.Element.SetAttributeValue("Text", "fernando_figliola@itrsa.com.ar");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Content1.EntryUrl' at Center", repo.ComAndroidKeepass.Content1.EntryUrlInfo, new RecordItemIndex(18));
            repo.ComAndroidKeepass.Content1.EntryUrl.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'https://webmail.itrsa.com.ar/' on item 'ComAndroidKeepass.Content1.EntryUrl'.", repo.ComAndroidKeepass.Content1.EntryUrlInfo, new RecordItemIndex(19));
            repo.ComAndroidKeepass.Content1.EntryUrl.Element.SetAttributeValue("Text", "https://webmail.itrsa.com.ar/");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.Content1.GenerateButton' at Center", repo.ComAndroidKeepass.Content1.GenerateButtonInfo, new RecordItemIndex(20));
            repo.ComAndroidKeepass.Content1.GenerateButton.Touch();
            Delay.Milliseconds(500);
            
            // Seccion Genera Contraseña
            Report.Log(ReportLevel.Info, "Section", "Seccion Genera Contraseña", new RecordItemIndex(21));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComAndroidKeepass.Self, false, new RecordItemIndex(22));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GeneratePasswordActivity.BtnLength12' at Center", repo.ComAndroidKeepass.GeneratePasswordActivity.BtnLength12Info, new RecordItemIndex(23));
            repo.ComAndroidKeepass.GeneratePasswordActivity.BtnLength12.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GeneratePasswordActivity.GeneratePasswordButton' at Center", repo.ComAndroidKeepass.GeneratePasswordActivity.GeneratePasswordButtonInfo, new RecordItemIndex(24));
            repo.ComAndroidKeepass.GeneratePasswordActivity.GeneratePasswordButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComAndroidKeepass.Self, false, new RecordItemIndex(25));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GeneratePasswordActivity.AcceptButton' at Center", repo.ComAndroidKeepass.GeneratePasswordActivity.AcceptButtonInfo, new RecordItemIndex(26));
            repo.ComAndroidKeepass.GeneratePasswordActivity.AcceptButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComAndroidKeepass.Self, false, new RecordItemIndex(27));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntrySave' at Center", repo.ComAndroidKeepass.EntrySaveInfo, new RecordItemIndex(28));
            repo.ComAndroidKeepass.EntrySave.Touch();
            Delay.Milliseconds(500);
            
            // Finalizacion
            Report.Log(ReportLevel.Info, "Section", "Finalizacion", new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComAndroidKeepass.Content.ITRMail'.", repo.ComAndroidKeepass.Content.ITRMailInfo, new RecordItemIndex(30));
            Validate.Exists(repo.ComAndroidKeepass.Content.ITRMailInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComAndroidKeepass.Self, false, new RecordItemIndex(31));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ComAndroidKeepass'.", repo.ComAndroidKeepass.SelfInfo, new RecordItemIndex(32));
            repo.ComAndroidKeepass.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ComAndroidKeepass.Content.Raiz'", repo.ComAndroidKeepass.Content.RaizInfo, new ActionTimeout(30000), new RecordItemIndex(33));
            repo.ComAndroidKeepass.Content.RaizInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
