///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PruebaOneDrive.Navegacion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CrearCarpeta recording.
    /// </summary>
    [TestModule("bee16ade-310e-48c3-bd3f-e0d05c329580", ModuleType.Recording, 1)]
    public partial class CrearCarpeta : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PruebaOneDrive.PruebaOneDriveRepository repository.
        /// </summary>
        public static global::PruebaOneDrive.PruebaOneDriveRepository repo = global::PruebaOneDrive.PruebaOneDriveRepository.Instance;

        static CrearCarpeta instance = new CrearCarpeta();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CrearCarpeta()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CrearCarpeta Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.Nuevo' at Center.", repo.SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.NuevoInfo, new RecordItemIndex(0));
            repo.SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.Nuevo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.Carpeta'", repo.SignInMicrosoftOneDrive.CarpetaInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SignInMicrosoftOneDrive.CarpetaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.Carpeta' at CenterLeft.", repo.SignInMicrosoftOneDrive.CarpetaInfo, new RecordItemIndex(2));
            repo.SignInMicrosoftOneDrive.Carpeta.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.lbl_Carpeta'", repo.SignInMicrosoftOneDrive.lbl_CarpetaInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.SignInMicrosoftOneDrive.lbl_CarpetaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.Text' at CenterLeft.", repo.SignInMicrosoftOneDrive.TextInfo, new RecordItemIndex(4));
            repo.SignInMicrosoftOneDrive.Text.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PruebaWebinear' with focus on 'SignInMicrosoftOneDrive.Text'.", repo.SignInMicrosoftOneDrive.TextInfo, new RecordItemIndex(5));
            repo.SignInMicrosoftOneDrive.Text.PressKeys("PruebaWebinear");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.Crear' at Center.", repo.SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.CrearInfo, new RecordItemIndex(6));
            repo.SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.Crear.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinear'", repo.SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinearInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.SignInMicrosoftOneDrive.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinearInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(8));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
