///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PruebaOneDrive.Navegacion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubirArchivo recording.
    /// </summary>
    [TestModule("3ef934c2-4cfc-4837-8dac-e448d493de77", ModuleType.Recording, 1)]
    public partial class SubirArchivo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PruebaOneDrive.PruebaOneDriveRepository repository.
        /// </summary>
        public static global::PruebaOneDrive.PruebaOneDriveRepository repo = global::PruebaOneDrive.PruebaOneDriveRepository.Instance;

        static SubirArchivo instance = new SubirArchivo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubirArchivo()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubirArchivo Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.AppRoot.Cargar' at 15;12.", repo.SignInMicrosoftOneDrive.AppRoot.CargarInfo, new RecordItemIndex(0));
            repo.SignInMicrosoftOneDrive.AppRoot.Cargar.Click("15;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.Archivos'", repo.SignInMicrosoftOneDrive.ArchivosInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SignInMicrosoftOneDrive.ArchivosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.Archivos' at 28;21.", repo.SignInMicrosoftOneDrive.ArchivosInfo, new RecordItemIndex(2));
            repo.SignInMicrosoftOneDrive.Archivos.Click("28;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'Abrir'", repo.Abrir.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.Abrir.SelfInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.Escritorio' at 9;7.", repo.Abrir.EscritorioInfo, new RecordItemIndex(4));
            repo.Abrir.Escritorio.Click("9;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\TEMP{Return}'.", new RecordItemIndex(5));
            Keyboard.Press("C:\\TEMP{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.Text1148' at CenterLeft.", repo.Abrir.Text1148Info, new RecordItemIndex(6));
            repo.Abrir.Text1148.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'pruebaWeb.txt' with focus on 'Abrir.Text1148'.", repo.Abrir.Text1148Info, new RecordItemIndex(7));
            repo.Abrir.Text1148.PressKeys("pruebaWeb.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.ButtonAbrir' at Center.", repo.Abrir.ButtonAbrirInfo, new RecordItemIndex(8));
            repo.Abrir.ButtonAbrir.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.AppRoot.PruebaWebTxt'", repo.SignInMicrosoftOneDrive.AppRoot.PruebaWebTxtInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.SignInMicrosoftOneDrive.AppRoot.PruebaWebTxtInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(10));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
