///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PruebaOneDrive.Navegacion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validacion recording.
    /// </summary>
    [TestModule("441f4bc7-a60f-4664-b706-3a0c59678833", ModuleType.Recording, 1)]
    public partial class Validacion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PruebaOneDrive.PruebaOneDriveRepository repository.
        /// </summary>
        public static global::PruebaOneDrive.PruebaOneDriveRepository repo = global::PruebaOneDrive.PruebaOneDriveRepository.Instance;

        static Validacion instance = new Validacion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validacion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validacion Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInMicrosoftOneDrive.AppRoot.MisArchivos' at 39;12.", repo.SignInMicrosoftOneDrive.AppRoot.MisArchivosInfo, new RecordItemIndex(0));
            repo.SignInMicrosoftOneDrive.AppRoot.MisArchivos.Click("39;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInMicrosoftOneDrive.AlmacenPersonal'", repo.SignInMicrosoftOneDrive.AlmacenPersonalInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SignInMicrosoftOneDrive.AlmacenPersonalInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'SignInMicrosoftOneDriver_COF.Copy_of_CarpetaCreada'.", repo.SignInMicrosoftOneDriver_COF.Copy_of_CarpetaCreadaInfo, new RecordItemIndex(3));
            Validate.NotExists(repo.SignInMicrosoftOneDriver_COF.Copy_of_CarpetaCreadaInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
