///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CrearCarpeta recording.
    /// </summary>
    [TestModule("c7b00e0c-fc40-4602-8975-e9bcfe21a19f", ModuleType.Recording, 1)]
    public partial class CrearCarpeta : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebRepository repository.
        /// </summary>
        public static WebRepository repo = WebRepository.Instance;

        static CrearCarpeta instance = new CrearCarpeta();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CrearCarpeta()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CrearCarpeta Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Nuevo' at Center.", repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.NuevoInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Nuevo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Carpeta' at Center.", repo.ApplicationUnderTest.CarpetaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Carpeta.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.OdDialogTitle'", repo.ApplicationUnderTest.OdDialogTitleInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.ApplicationUnderTest.OdDialogTitleInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text' at CenterLeft.", repo.ApplicationUnderTest.TextInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Text.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PruebaWebinear' with focus on 'ApplicationUnderTest.Text'.", repo.ApplicationUnderTest.TextInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Text.PressKeys("PruebaWebinear");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Crear' at Center.", repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.CrearInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Crear.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinear'", repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinearInfo, new ActionTimeout(30000), new RecordItemIndex(6));
            repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinearInfo.WaitForNotExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(7));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
