///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubirArchivo recording.
    /// </summary>
    [TestModule("463a96a4-d1af-4b2c-885b-974345078d7b", ModuleType.Recording, 1)]
    public partial class SubirArchivo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebRepository repository.
        /// </summary>
        public static WebRepository repo = WebRepository.Instance;

        static SubirArchivo instance = new SubirArchivo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubirArchivo()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubirArchivo Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinear' at Center.", repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinearInfo, new RecordItemIndex(0));
            //repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebinear.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Cargar_Bis' at Center.", repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Cargar_BisInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.Cargar_Bis.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Archivos' at Center.", repo.ApplicationUnderTest.ArchivosInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Archivos.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.Escritorio' at 14;13.", repo.Abrir.EscritorioInfo, new RecordItemIndex(3));
            repo.Abrir.Escritorio.Click("14;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\TEMP' with focus on 'Abrir'.", repo.Abrir.SelfInfo, new RecordItemIndex(4));
            repo.Abrir.Self.EnsureVisible();
            Keyboard.Press("C:\\TEMP");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.Text1148' at CenterLeft.", repo.Abrir.Text1148Info, new RecordItemIndex(5));
            repo.Abrir.Text1148.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'pruebaWeb.txt' with focus on 'Abrir.Text1148'.", repo.Abrir.Text1148Info, new RecordItemIndex(6));
            repo.Abrir.Text1148.PressKeys("pruebaWeb.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.ButtonAbrir' at Center.", repo.Abrir.ButtonAbrirInfo, new RecordItemIndex(7));
            repo.Abrir.ButtonAbrir.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebTxt'", repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebTxtInfo, new ActionTimeout(30000), new RecordItemIndex(8));
            repo.ApplicationUnderTest.OdBasePageOdBasePageLeftNavVisibleO.PruebaWebTxtInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(9));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
