///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("06fb0bcf-3770-45c2-a755-52da37adeb54")]
    public partial class WebRepository : RepoGenBaseFolder
    {
        static WebRepository instance = new WebRepository();
        WebRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        WebRepositoryFolders.OneDriveAppFolder _onedrive;
        WebRepositoryFolders.AbrirAppFolder _abrir;
        WebRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder _personalcloudstoragemicrosoftonedri;

        /// <summary>
        /// Gets the singleton class instance representing the WebRepository element repository.
        /// </summary>
        [RepositoryFolder("06fb0bcf-3770-45c2-a755-52da37adeb54")]
        public static WebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebRepository() 
            : base("WebRepository", "/", null, 0, false, "06fb0bcf-3770-45c2-a755-52da37adeb54", ".\\RepositoryImages\\WebRepository06fb0bcf.rximgres")
        {
            _applicationundertest = new WebRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _onedrive = new WebRepositoryFolders.OneDriveAppFolder(this);
            _abrir = new WebRepositoryFolders.AbrirAppFolder(this);
            _personalcloudstoragemicrosoftonedri = new WebRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("06fb0bcf-3770-45c2-a755-52da37adeb54")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("7e31385b-8c33-4635-9632-48cc1a64e5d9")]
        public virtual WebRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The OneDrive folder.
        /// </summary>
        [RepositoryFolder("17a4b5a8-b2d1-4398-b096-e1fdb5a65637")]
        public virtual WebRepositoryFolders.OneDriveAppFolder OneDrive
        {
            get { return _onedrive; }
        }

        /// <summary>
        /// The Abrir folder.
        /// </summary>
        [RepositoryFolder("cf913e62-8f8e-4082-ba1b-5c37430d3067")]
        public virtual WebRepositoryFolders.AbrirAppFolder Abrir
        {
            get { return _abrir; }
        }

        /// <summary>
        /// The PersonalCloudStorageMicrosoftOneDri folder.
        /// </summary>
        [RepositoryFolder("8a14f62c-1266-41bc-80bb-32bb9c9e33f8")]
        public virtual WebRepositoryFolders.PersonalCloudStorageMicrosoftOneDriAppFolder PersonalCloudStorageMicrosoftOneDri
        {
            get { return _personalcloudstoragemicrosoftonedri; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WebRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("7e31385b-8c33-4635-9632-48cc1a64e5d9")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            WebRepositoryFolders.SomeDivTagFolder _somedivtag;
            WebRepositoryFolders.OdBasePageOdBasePageLeftNavVisibleOFolder _odbasepageodbasepageleftnavvisibleo;
            RepoItemInfo _almacenpersonalInfo;
            RepoItemInfo _carpetaInfo;
            RepoItemInfo _oddialogtitleInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _archivosInfo;
            RepoItemInfo _mecontrolsignoutlinkInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='onedrive.live.com']", parentFolder, 30000, null, false, "7e31385b-8c33-4635-9632-48cc1a64e5d9", "")
            {
                _somedivtag = new WebRepositoryFolders.SomeDivTagFolder(this);
                _odbasepageodbasepageleftnavvisibleo = new WebRepositoryFolders.OdBasePageOdBasePageLeftNavVisibleOFolder(this);
                _almacenpersonalInfo = new RepoItemInfo(this, "AlmacenPersonal", ".//div[#'appRoot']/div/div[2]/div[5]/main/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div/div[1]/div/div/div/a[@href>'https://onedrive.live.com']/span[3]/span[1]//span[@innertext='Almacén personal']", 30000, null, "b77633e1-5b60-47ba-a66a-aebf949bbf6b");
                _carpetaInfo = new RepoItemInfo(this, "Carpeta", "body/div[3]/div//ul/li[@title='Carpeta']/button[@title='Carpeta']/?/?/span[@innertext='Carpeta']", 30000, null, "d092a16d-ce63-4c3e-be1c-018625b37133");
                _oddialogtitleInfo = new RepoItemInfo(this, "OdDialogTitle", ".//p[#'od-Dialog-title']", 30000, null, "7d148092-434a-46e4-b111-c21662bd9254");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'od-Dialog-content']//input[@type='text']", 30000, null, "4542044a-2ae5-43a6-a8e2-af75a60727bc");
                _archivosInfo = new RepoItemInfo(this, "Archivos", "body/div[3]/div//ul/li[@title='Archivos']/button[@title='Archivos']/?/?/span[@innertext='Archivos']", 30000, null, "04e14dde-174f-46c6-9833-7cd8b035d160");
                _mecontrolsignoutlinkInfo = new RepoItemInfo(this, "MeControlSignoutLink", ".//a[#'meControlSignoutLink']", 30000, null, "7066587e-7468-4405-9953-b8af7b3300bb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7e31385b-8c33-4635-9632-48cc1a64e5d9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7e31385b-8c33-4635-9632-48cc1a64e5d9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AlmacenPersonal item.
            /// </summary>
            [RepositoryItem("b77633e1-5b60-47ba-a66a-aebf949bbf6b")]
            public virtual Ranorex.SpanTag AlmacenPersonal
            {
                get
                {
                    return _almacenpersonalInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AlmacenPersonal item info.
            /// </summary>
            [RepositoryItemInfo("b77633e1-5b60-47ba-a66a-aebf949bbf6b")]
            public virtual RepoItemInfo AlmacenPersonalInfo
            {
                get
                {
                    return _almacenpersonalInfo;
                }
            }

            /// <summary>
            /// The Carpeta item.
            /// </summary>
            [RepositoryItem("d092a16d-ce63-4c3e-be1c-018625b37133")]
            public virtual Ranorex.SpanTag Carpeta
            {
                get
                {
                    return _carpetaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Carpeta item info.
            /// </summary>
            [RepositoryItemInfo("d092a16d-ce63-4c3e-be1c-018625b37133")]
            public virtual RepoItemInfo CarpetaInfo
            {
                get
                {
                    return _carpetaInfo;
                }
            }

            /// <summary>
            /// The OdDialogTitle item.
            /// </summary>
            [RepositoryItem("7d148092-434a-46e4-b111-c21662bd9254")]
            public virtual Ranorex.PTag OdDialogTitle
            {
                get
                {
                    return _oddialogtitleInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The OdDialogTitle item info.
            /// </summary>
            [RepositoryItemInfo("7d148092-434a-46e4-b111-c21662bd9254")]
            public virtual RepoItemInfo OdDialogTitleInfo
            {
                get
                {
                    return _oddialogtitleInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("4542044a-2ae5-43a6-a8e2-af75a60727bc")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("4542044a-2ae5-43a6-a8e2-af75a60727bc")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Archivos item.
            /// </summary>
            [RepositoryItem("04e14dde-174f-46c6-9833-7cd8b035d160")]
            public virtual Ranorex.SpanTag Archivos
            {
                get
                {
                    return _archivosInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Archivos item info.
            /// </summary>
            [RepositoryItemInfo("04e14dde-174f-46c6-9833-7cd8b035d160")]
            public virtual RepoItemInfo ArchivosInfo
            {
                get
                {
                    return _archivosInfo;
                }
            }

            /// <summary>
            /// The MeControlSignoutLink item.
            /// </summary>
            [RepositoryItem("7066587e-7468-4405-9953-b8af7b3300bb")]
            public virtual Ranorex.ATag MeControlSignoutLink
            {
                get
                {
                    return _mecontrolsignoutlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MeControlSignoutLink item info.
            /// </summary>
            [RepositoryItemInfo("7066587e-7468-4405-9953-b8af7b3300bb")]
            public virtual RepoItemInfo MeControlSignoutLinkInfo
            {
                get
                {
                    return _mecontrolsignoutlinkInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag folder.
            /// </summary>
            [RepositoryFolder("16c4dcc6-326c-4d08-a78f-f96933d793d5")]
            public virtual WebRepositoryFolders.SomeDivTagFolder SomeDivTag
            {
                get { return _somedivtag; }
            }

            /// <summary>
            /// The OdBasePageOdBasePageLeftNavVisibleO folder.
            /// </summary>
            [RepositoryFolder("4f423320-e609-48e5-9556-5a8154ff3cd9")]
            public virtual WebRepositoryFolders.OdBasePageOdBasePageLeftNavVisibleOFolder OdBasePageOdBasePageLeftNavVisibleO
            {
                get { return _odbasepageodbasepageleftnavvisibleo; }
            }
        }

        /// <summary>
        /// The SomeDivTagFolder folder.
        /// </summary>
        [RepositoryFolder("16c4dcc6-326c-4d08-a78f-f96933d793d5")]
        public partial class SomeDivTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailInfo;
            RepoItemInfo _personalaccountInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new SomeDivTag  folder.
            /// </summary>
            public SomeDivTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeDivTag", ".//section[#'mainContent']/iframe[@src='https://odc.officeapps.live.com/odc/v2.0/hrd?rs=en-us&Ver=16&app=23&p=6&hm=0']/body/div[2]/?/?/main/div[2]", parentFolder, 30000, null, false, "16c4dcc6-326c-4d08-a78f-f96933d793d5", "")
            {
                _emailInfo = new RepoItemInfo(this, "Email", "div[2]/?/?/input[@type='email']", 30000, null, "17aa4547-a969-488a-9bd2-f665d7bd2f56");
                _personalaccountInfo = new RepoItemInfo(this, "PersonalAccount", "div[3]/?/?/div[@innertext='Personal account']", 30000, null, "61684cab-29f2-48e7-8167-9f2010eab360");
                _submitInfo = new RepoItemInfo(this, "Submit", "div[4]/input[@type='submit']", 30000, null, "9c1483c9-ee52-4964-a9bb-4f59585d0184");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16c4dcc6-326c-4d08-a78f-f96933d793d5")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16c4dcc6-326c-4d08-a78f-f96933d793d5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("17aa4547-a969-488a-9bd2-f665d7bd2f56")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("17aa4547-a969-488a-9bd2-f665d7bd2f56")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The PersonalAccount item.
            /// </summary>
            [RepositoryItem("61684cab-29f2-48e7-8167-9f2010eab360")]
            public virtual Ranorex.DivTag PersonalAccount
            {
                get
                {
                    return _personalaccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PersonalAccount item info.
            /// </summary>
            [RepositoryItemInfo("61684cab-29f2-48e7-8167-9f2010eab360")]
            public virtual RepoItemInfo PersonalAccountInfo
            {
                get
                {
                    return _personalaccountInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("9c1483c9-ee52-4964-a9bb-4f59585d0184")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("9c1483c9-ee52-4964-a9bb-4f59585d0184")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

        /// <summary>
        /// The OdBasePageOdBasePageLeftNavVisibleOFolder folder.
        /// </summary>
        [RepositoryFolder("4f423320-e609-48e5-9556-5a8154ff3cd9")]
        public partial class OdBasePageOdBasePageLeftNavVisibleOFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nuevoInfo;
            RepoItemInfo _pruebawebinearInfo;
            RepoItemInfo _crearInfo;
            RepoItemInfo _cargarInfo;
            RepoItemInfo _pruebawebtxtInfo;
            RepoItemInfo _imgtagfInfo;
            RepoItemInfo _cargar_bisInfo;

            /// <summary>
            /// Creates a new OdBasePageOdBasePageLeftNavVisibleO  folder.
            /// </summary>
            public OdBasePageOdBasePageLeftNavVisibleOFolder(RepoGenBaseFolder parentFolder) :
                    base("OdBasePageOdBasePageLeftNavVisibleO", ".//div[#'appRoot']/div", parentFolder, 30000, null, false, "4f423320-e609-48e5-9556-5a8154ff3cd9", "")
            {
                _nuevoInfo = new RepoItemInfo(this, "Nuevo", "div[2]/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div[1]/div[1]/button[@title>'Crear una carpeta o un documento']/span/span/span[@innertext='Nuevo']", 30000, null, "5926fc75-d1e2-4b3e-bf49-9f24fdd21c8a");
                _pruebawebinearInfo = new RepoItemInfo(this, "PruebaWebinear", "div[2]/div[5]/main/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div/div[4]//a[@href>'https://onedrive.live.com']/span[3]/span[1]/span/span[2]/span[@innertext='PruebaWebinear']", 30000, null, "5378b173-6c89-4a7f-a61d-3684f4b14858");
                _crearInfo = new RepoItemInfo(this, "Crear", "div[5]/div/div/div/div/div[2]/div/div/div[2]/div[2]//span[@innertext='Crear']", 30000, null, "0ee20c3b-9e92-4970-9d3d-bae286b384f6");
                _cargarInfo = new RepoItemInfo(this, "Cargar", "div[2]/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div[1]/div[2]/button[@title>'Cargar archivos de tu equipo']/span/span/*[@innertext='Cargar']", 30000, null, "294f3e8b-fec1-4744-82de-ad2359f55c27");
                _pruebawebtxtInfo = new RepoItemInfo(this, "PruebaWebTxt", "div[2]/div[5]/main/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/a[@href>'https://onedrive.live.com']/span[3]/span[1]/span/span[2]/span[@innertext='pruebaWeb.txt']", 30000, null, "97e03dfb-d0a8-4189-868f-55615948d767");
                _imgtagfInfo = new RepoItemInfo(this, "ImgTagF", "div[1]/div/div[1]/div[3]/div[1]/button[@title>'Administrador de cuenta para']/div/div[2]//img[@alt='F']", 30000, null, "98aafe01-98b5-4938-8f6b-6be70a53befc");
                _cargar_bisInfo = new RepoItemInfo(this, "Cargar_Bis", "div[2]/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div[1]/div[2]/button[@title>'Cargar archivos de tu equipo']/span", 30000, null, "ea44f883-c1b5-4eca-9f58-6dedc3a4c8ed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f423320-e609-48e5-9556-5a8154ff3cd9")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f423320-e609-48e5-9556-5a8154ff3cd9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Nuevo item.
            /// </summary>
            [RepositoryItem("5926fc75-d1e2-4b3e-bf49-9f24fdd21c8a")]
            public virtual Ranorex.SpanTag Nuevo
            {
                get
                {
                    return _nuevoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Nuevo item info.
            /// </summary>
            [RepositoryItemInfo("5926fc75-d1e2-4b3e-bf49-9f24fdd21c8a")]
            public virtual RepoItemInfo NuevoInfo
            {
                get
                {
                    return _nuevoInfo;
                }
            }

            /// <summary>
            /// The PruebaWebinear item.
            /// </summary>
            [RepositoryItem("5378b173-6c89-4a7f-a61d-3684f4b14858")]
            public virtual Ranorex.SpanTag PruebaWebinear
            {
                get
                {
                    return _pruebawebinearInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PruebaWebinear item info.
            /// </summary>
            [RepositoryItemInfo("5378b173-6c89-4a7f-a61d-3684f4b14858")]
            public virtual RepoItemInfo PruebaWebinearInfo
            {
                get
                {
                    return _pruebawebinearInfo;
                }
            }

            /// <summary>
            /// The Crear item.
            /// </summary>
            [RepositoryItem("0ee20c3b-9e92-4970-9d3d-bae286b384f6")]
            public virtual Ranorex.SpanTag Crear
            {
                get
                {
                    return _crearInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Crear item info.
            /// </summary>
            [RepositoryItemInfo("0ee20c3b-9e92-4970-9d3d-bae286b384f6")]
            public virtual RepoItemInfo CrearInfo
            {
                get
                {
                    return _crearInfo;
                }
            }

            /// <summary>
            /// The Cargar item.
            /// </summary>
            [RepositoryItem("294f3e8b-fec1-4744-82de-ad2359f55c27")]
            public virtual Ranorex.Unknown Cargar
            {
                get
                {
                    return _cargarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Cargar item info.
            /// </summary>
            [RepositoryItemInfo("294f3e8b-fec1-4744-82de-ad2359f55c27")]
            public virtual RepoItemInfo CargarInfo
            {
                get
                {
                    return _cargarInfo;
                }
            }

            /// <summary>
            /// The PruebaWebTxt item.
            /// </summary>
            [RepositoryItem("97e03dfb-d0a8-4189-868f-55615948d767")]
            public virtual Ranorex.SpanTag PruebaWebTxt
            {
                get
                {
                    return _pruebawebtxtInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PruebaWebTxt item info.
            /// </summary>
            [RepositoryItemInfo("97e03dfb-d0a8-4189-868f-55615948d767")]
            public virtual RepoItemInfo PruebaWebTxtInfo
            {
                get
                {
                    return _pruebawebtxtInfo;
                }
            }

            /// <summary>
            /// The ImgTagF item.
            /// </summary>
            [RepositoryItem("98aafe01-98b5-4938-8f6b-6be70a53befc")]
            public virtual Ranorex.ImgTag ImgTagF
            {
                get
                {
                    return _imgtagfInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgTagF item info.
            /// </summary>
            [RepositoryItemInfo("98aafe01-98b5-4938-8f6b-6be70a53befc")]
            public virtual RepoItemInfo ImgTagFInfo
            {
                get
                {
                    return _imgtagfInfo;
                }
            }

            /// <summary>
            /// The Cargar_Bis item.
            /// </summary>
            [RepositoryItem("ea44f883-c1b5-4eca-9f58-6dedc3a4c8ed")]
            public virtual Ranorex.SpanTag Cargar_Bis
            {
                get
                {
                    return _cargar_bisInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Cargar_Bis item info.
            /// </summary>
            [RepositoryItemInfo("ea44f883-c1b5-4eca-9f58-6dedc3a4c8ed")]
            public virtual RepoItemInfo Cargar_BisInfo
            {
                get
                {
                    return _cargar_bisInfo;
                }
            }
        }

        /// <summary>
        /// The OneDriveAppFolder folder.
        /// </summary>
        [RepositoryFolder("17a4b5a8-b2d1-4398-b096-e1fdb5a65637")]
        public partial class OneDriveAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fadeinlightboxinnerInfo;
            RepoItemInfo _passwdInfo;
            RepoItemInfo _idsibutton9Info;

            /// <summary>
            /// Creates a new OneDrive  folder.
            /// </summary>
            public OneDriveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OneDrive", "/dom[@domain='login.live.com']", parentFolder, 30000, null, false, "17a4b5a8-b2d1-4398-b096-e1fdb5a65637", "")
            {
                _fadeinlightboxinnerInfo = new RepoItemInfo(this, "FadeInLightboxInner", "body/?/?/form[@name='f1']/div/div/div[1]", 30000, null, "3f477fa6-220d-416e-abf3-f3e522ef64f0");
                _passwdInfo = new RepoItemInfo(this, "Passwd", "body/?/?/form[@name='f1']/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div[2]//input[@name='passwd']", 30000, null, "b59a77ad-43dc-460d-a5cb-3c99ba672001");
                _idsibutton9Info = new RepoItemInfo(this, "IdSIButton9", ".//input[#'idSIButton9']", 30000, null, "0d89cd7f-47b3-4d55-b242-d9888d519740");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17a4b5a8-b2d1-4398-b096-e1fdb5a65637")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17a4b5a8-b2d1-4398-b096-e1fdb5a65637")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FadeInLightboxInner item.
            /// </summary>
            [RepositoryItem("3f477fa6-220d-416e-abf3-f3e522ef64f0")]
            public virtual Ranorex.DivTag FadeInLightboxInner
            {
                get
                {
                    return _fadeinlightboxinnerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FadeInLightboxInner item info.
            /// </summary>
            [RepositoryItemInfo("3f477fa6-220d-416e-abf3-f3e522ef64f0")]
            public virtual RepoItemInfo FadeInLightboxInnerInfo
            {
                get
                {
                    return _fadeinlightboxinnerInfo;
                }
            }

            /// <summary>
            /// The Passwd item.
            /// </summary>
            [RepositoryItem("b59a77ad-43dc-460d-a5cb-3c99ba672001")]
            public virtual Ranorex.InputTag Passwd
            {
                get
                {
                    return _passwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Passwd item info.
            /// </summary>
            [RepositoryItemInfo("b59a77ad-43dc-460d-a5cb-3c99ba672001")]
            public virtual RepoItemInfo PasswdInfo
            {
                get
                {
                    return _passwdInfo;
                }
            }

            /// <summary>
            /// The IdSIButton9 item.
            /// </summary>
            [RepositoryItem("0d89cd7f-47b3-4d55-b242-d9888d519740")]
            public virtual Ranorex.InputTag IdSIButton9
            {
                get
                {
                    return _idsibutton9Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IdSIButton9 item info.
            /// </summary>
            [RepositoryItemInfo("0d89cd7f-47b3-4d55-b242-d9888d519740")]
            public virtual RepoItemInfo IdSIButton9Info
            {
                get
                {
                    return _idsibutton9Info;
                }
            }
        }

        /// <summary>
        /// The AbrirAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf913e62-8f8e-4082-ba1b-5c37430d3067")]
        public partial class AbrirAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _escritorioInfo;
            RepoItemInfo _text1148Info;
            RepoItemInfo _buttonabrirInfo;

            /// <summary>
            /// Creates a new Abrir  folder.
            /// </summary>
            public AbrirAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Abrir", "/form[@title='Abrir']", parentFolder, 30000, null, true, "cf913e62-8f8e-4082-ba1b-5c37430d3067", "")
            {
                _escritorioInfo = new RepoItemInfo(this, "Escritorio", "element[@class='WorkerW']/container[@controlid='40965']//toolbar[@controlid='1001']/button[@text='Escritorio']", 30000, null, "e69d8a44-58de-45d7-813d-04e226514d5a");
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", 30000, null, "525f55bf-9c5a-435e-8157-df18241dead8");
                _buttonabrirInfo = new RepoItemInfo(this, "ButtonAbrir", "button[@text='&Abrir']", 30000, null, "aa1be551-6969-4dfd-a8bb-294968063c87");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf913e62-8f8e-4082-ba1b-5c37430d3067")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf913e62-8f8e-4082-ba1b-5c37430d3067")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Escritorio item.
            /// </summary>
            [RepositoryItem("e69d8a44-58de-45d7-813d-04e226514d5a")]
            public virtual Ranorex.Button Escritorio
            {
                get
                {
                    return _escritorioInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Escritorio item info.
            /// </summary>
            [RepositoryItemInfo("e69d8a44-58de-45d7-813d-04e226514d5a")]
            public virtual RepoItemInfo EscritorioInfo
            {
                get
                {
                    return _escritorioInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("525f55bf-9c5a-435e-8157-df18241dead8")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("525f55bf-9c5a-435e-8157-df18241dead8")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The ButtonAbrir item.
            /// </summary>
            [RepositoryItem("aa1be551-6969-4dfd-a8bb-294968063c87")]
            public virtual Ranorex.Button ButtonAbrir
            {
                get
                {
                    return _buttonabrirInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAbrir item info.
            /// </summary>
            [RepositoryItemInfo("aa1be551-6969-4dfd-a8bb-294968063c87")]
            public virtual RepoItemInfo ButtonAbrirInfo
            {
                get
                {
                    return _buttonabrirInfo;
                }
            }
        }

        /// <summary>
        /// The PersonalCloudStorageMicrosoftOneDriAppFolder folder.
        /// </summary>
        [RepositoryFolder("8a14f62c-1266-41bc-80bb-32bb9c9e33f8")]
        public partial class PersonalCloudStorageMicrosoftOneDriAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpsgomicrosoftcomfwlinkplinkidInfo;

            /// <summary>
            /// Creates a new PersonalCloudStorageMicrosoftOneDri  folder.
            /// </summary>
            public PersonalCloudStorageMicrosoftOneDriAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PersonalCloudStorageMicrosoftOneDri", "/dom[@domain='www.microsoft.com']", parentFolder, 30000, null, false, "8a14f62c-1266-41bc-80bb-32bb9c9e33f8", "")
            {
                _httpsgomicrosoftcomfwlinkplinkidInfo = new RepoItemInfo(this, "HttpsGoMicrosoftComFwlinkPLinkID", ".//div[#'heroregion']/?/?/section/div/div/div/div/div/div/div[1]/a[@href>'https://go.microsoft.com/']", 30000, null, "f09ec31d-ca36-4a53-948e-90341aa3865a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8a14f62c-1266-41bc-80bb-32bb9c9e33f8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a14f62c-1266-41bc-80bb-32bb9c9e33f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsGoMicrosoftComFwlinkPLinkID item.
            /// </summary>
            [RepositoryItem("f09ec31d-ca36-4a53-948e-90341aa3865a")]
            public virtual Ranorex.ATag HttpsGoMicrosoftComFwlinkPLinkID
            {
                get
                {
                    return _httpsgomicrosoftcomfwlinkplinkidInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsGoMicrosoftComFwlinkPLinkID item info.
            /// </summary>
            [RepositoryItemInfo("f09ec31d-ca36-4a53-948e-90341aa3865a")]
            public virtual RepoItemInfo HttpsGoMicrosoftComFwlinkPLinkIDInfo
            {
                get
                {
                    return _httpsgomicrosoftcomfwlinkplinkidInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
