///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("92b0dab7-fe66-4f03-982d-667528682b36")]
    public partial class DesktopRepository : RepoGenBaseFolder
    {
        static DesktopRepository instance = new DesktopRepository();
        DesktopRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        DesktopRepositoryFolders.MainFormAppFolder _mainform;
        DesktopRepositoryFolders.KeePassAppFolder _keepass;
        DesktopRepositoryFolders.PwEntryFormAppFolder _pwentryform;

        /// <summary>
        /// Gets the singleton class instance representing the DesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("92b0dab7-fe66-4f03-982d-667528682b36")]
        public static DesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopRepository() 
            : base("DesktopRepository", "/", null, 0, false, "92b0dab7-fe66-4f03-982d-667528682b36", ".\\RepositoryImages\\DesktopRepository92b0dab7.rximgres")
        {
            _keypromptform = new DesktopRepositoryFolders.KeyPromptFormAppFolder(this);
            _mainform = new DesktopRepositoryFolders.MainFormAppFolder(this);
            _keepass = new DesktopRepositoryFolders.KeePassAppFolder(this);
            _pwentryform = new DesktopRepositoryFolders.PwEntryFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("92b0dab7-fe66-4f03-982d-667528682b36")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("5a37c230-1644-4994-982f-a3aba29375d4")]
        public virtual DesktopRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("e42b5f67-28b0-49b1-8977-bdc6f217b2d0")]
        public virtual DesktopRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("8c64bdfc-5ccb-4514-b680-d227cb59159f")]
        public virtual DesktopRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The PwEntryForm folder.
        /// </summary>
        [RepositoryFolder("2f1bf519-a538-4ede-811d-7485d7fe4f1a")]
        public virtual DesktopRepositoryFolders.PwEntryFormAppFolder PwEntryForm
        {
            get { return _pwentryform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DesktopRepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("5a37c230-1644-4994-982f-a3aba29375d4")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mbannerimageInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "5a37c230-1644-4994-982f-a3aba29375d4", "")
            {
                _mbannerimageInfo = new RepoItemInfo(this, "MBannerImage", "picture[@controlname='m_bannerImage']", 30000, null, "9b3f25c1-767e-484a-9dee-1788d00df4ee");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "20c2b975-151e-4ef8-9b46-25c2feb1b4ee");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "91492f6f-57d7-411a-a94c-6dd284a57825");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5a37c230-1644-4994-982f-a3aba29375d4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a37c230-1644-4994-982f-a3aba29375d4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MBannerImage item.
            /// </summary>
            [RepositoryItem("9b3f25c1-767e-484a-9dee-1788d00df4ee")]
            public virtual Ranorex.Picture MBannerImage
            {
                get
                {
                    return _mbannerimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The MBannerImage item info.
            /// </summary>
            [RepositoryItemInfo("9b3f25c1-767e-484a-9dee-1788d00df4ee")]
            public virtual RepoItemInfo MBannerImageInfo
            {
                get
                {
                    return _mbannerimageInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("20c2b975-151e-4ef8-9b46-25c2feb1b4ee")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("20c2b975-151e-4ef8-9b46-25c2feb1b4ee")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("91492f6f-57d7-411a-a94c-6dd284a57825")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("91492f6f-57d7-411a-a94c-6dd284a57825")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("e42b5f67-28b0-49b1-8977-bdc6f217b2d0")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _databaseInfo;
            RepoItemInfo _entryInfo;
            RepoItemInfo _pruebawebineardesktopInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "e42b5f67-28b0-49b1-8977-bdc6f217b2d0", "")
            {
                _databaseInfo = new RepoItemInfo(this, "Database", "container[@controlname='m_splitHorizontal']/?/?/container[@controlname='m_splitVertical']/?/?/tree[@controlname='m_tvGroups']/?/?/treeitem[@accessiblename='Database']", 30000, null, "02881df6-2f8c-4d03-988b-842ae58c6b05");
                _entryInfo = new RepoItemInfo(this, "Entry", "?/?/menuitem[@accessiblename='Entry']", 30000, null, "17190efe-1fc7-4b56-8be6-74d0160e94bc");
                _pruebawebineardesktopInfo = new RepoItemInfo(this, "PruebaWebinearDesktop", "container[@controlname='m_splitHorizontal']/?/?/container[@controlname='m_splitVertical']/?/?/table[@controlname='m_lvEntries']/?/?/cell[@text='PruebaWebinearDesktop']", 30000, null, "9e3a87b6-ac84-42a2-b5f3-c0f41be6acef");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/button[@accessiblename='Save']", 30000, null, "e3c3c322-1612-419e-ad84-dda6251b57c6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e42b5f67-28b0-49b1-8977-bdc6f217b2d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e42b5f67-28b0-49b1-8977-bdc6f217b2d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("02881df6-2f8c-4d03-988b-842ae58c6b05")]
            public virtual Ranorex.TreeItem Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("02881df6-2f8c-4d03-988b-842ae58c6b05")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The Entry item.
            /// </summary>
            [RepositoryItem("17190efe-1fc7-4b56-8be6-74d0160e94bc")]
            public virtual Ranorex.MenuItem Entry
            {
                get
                {
                    return _entryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Entry item info.
            /// </summary>
            [RepositoryItemInfo("17190efe-1fc7-4b56-8be6-74d0160e94bc")]
            public virtual RepoItemInfo EntryInfo
            {
                get
                {
                    return _entryInfo;
                }
            }

            /// <summary>
            /// The PruebaWebinearDesktop item.
            /// </summary>
            [RepositoryItem("9e3a87b6-ac84-42a2-b5f3-c0f41be6acef")]
            public virtual Ranorex.Cell PruebaWebinearDesktop
            {
                get
                {
                    return _pruebawebineardesktopInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The PruebaWebinearDesktop item info.
            /// </summary>
            [RepositoryItemInfo("9e3a87b6-ac84-42a2-b5f3-c0f41be6acef")]
            public virtual RepoItemInfo PruebaWebinearDesktopInfo
            {
                get
                {
                    return _pruebawebineardesktopInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("e3c3c322-1612-419e-ad84-dda6251b57c6")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("e3c3c322-1612-419e-ad84-dda6251b57c6")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("8c64bdfc-5ccb-4514-b680-d227cb59159f")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addentryInfo;
            RepoItemInfo _menuitemautomaticallygeneratedpassworInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, true, "8c64bdfc-5ccb-4514-b680-d227cb59159f", "")
            {
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "menuitem[@accessiblename='Add Entry...']", 30000, null, "7846d855-5255-46f1-9f6c-b33bfed9740c");
                _menuitemautomaticallygeneratedpassworInfo = new RepoItemInfo(this, "MenuItemAutomaticallyGeneratedPasswor", "menuitem[@accessiblename>'(Automatically generated passwords']", 30000, null, "1852b283-6b0e-4ee4-a9de-0be5bf65d97d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c64bdfc-5ccb-4514-b680-d227cb59159f")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c64bdfc-5ccb-4514-b680-d227cb59159f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("7846d855-5255-46f1-9f6c-b33bfed9740c")]
            public virtual Ranorex.MenuItem AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("7846d855-5255-46f1-9f6c-b33bfed9740c")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The MenuItemAutomaticallyGeneratedPasswor item.
            /// </summary>
            [RepositoryItem("1852b283-6b0e-4ee4-a9de-0be5bf65d97d")]
            public virtual Ranorex.MenuItem MenuItemAutomaticallyGeneratedPasswor
            {
                get
                {
                    return _menuitemautomaticallygeneratedpassworInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemAutomaticallyGeneratedPasswor item info.
            /// </summary>
            [RepositoryItemInfo("1852b283-6b0e-4ee4-a9de-0be5bf65d97d")]
            public virtual RepoItemInfo MenuItemAutomaticallyGeneratedPassworInfo
            {
                get
                {
                    return _menuitemautomaticallygeneratedpassworInfo;
                }
            }
        }

        /// <summary>
        /// The PwEntryFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("2f1bf519-a538-4ede-811d-7485d7fe4f1a")]
        public partial class PwEntryFormAppFolder : RepoGenBaseFolder
        {
            DesktopRepositoryFolders.MTabEntry1Folder _mtabentry1;
            RepoItemInfo _mbannerimageInfo;
            RepoItemInfo _autotypeInfo;
            RepoItemInfo _mcbautotypeenabledInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new PwEntryForm  folder.
            /// </summary>
            public PwEntryFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PwEntryForm", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "2f1bf519-a538-4ede-811d-7485d7fe4f1a", "")
            {
                _mtabentry1 = new DesktopRepositoryFolders.MTabEntry1Folder(this);
                _mbannerimageInfo = new RepoItemInfo(this, "MBannerImage", "picture[@controlname='m_bannerImage']", 30000, null, "91b665dc-d195-4084-8b11-e4721693a8ff");
                _autotypeInfo = new RepoItemInfo(this, "AutoType", "?/?/tabpage[@accessiblename='Auto-Type']", 30000, null, "e36423de-8d01-4396-a5ec-580143aabdfa");
                _mcbautotypeenabledInfo = new RepoItemInfo(this, "MCbAutoTypeEnabled", "?/?/tabpage[@controlname='m_tabAutoType']/checkbox[@controlname='m_cbAutoTypeEnabled']", 30000, null, "1872ec34-2555-48a1-851a-99b47d3ab92b");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "996c1bee-0a46-4380-9e29-2f408d726df3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f1bf519-a538-4ede-811d-7485d7fe4f1a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f1bf519-a538-4ede-811d-7485d7fe4f1a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MBannerImage item.
            /// </summary>
            [RepositoryItem("91b665dc-d195-4084-8b11-e4721693a8ff")]
            public virtual Ranorex.Picture MBannerImage
            {
                get
                {
                    return _mbannerimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The MBannerImage item info.
            /// </summary>
            [RepositoryItemInfo("91b665dc-d195-4084-8b11-e4721693a8ff")]
            public virtual RepoItemInfo MBannerImageInfo
            {
                get
                {
                    return _mbannerimageInfo;
                }
            }

            /// <summary>
            /// The AutoType item.
            /// </summary>
            [RepositoryItem("e36423de-8d01-4396-a5ec-580143aabdfa")]
            public virtual Ranorex.TabPage AutoType
            {
                get
                {
                    return _autotypeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The AutoType item info.
            /// </summary>
            [RepositoryItemInfo("e36423de-8d01-4396-a5ec-580143aabdfa")]
            public virtual RepoItemInfo AutoTypeInfo
            {
                get
                {
                    return _autotypeInfo;
                }
            }

            /// <summary>
            /// The MCbAutoTypeEnabled item.
            /// </summary>
            [RepositoryItem("1872ec34-2555-48a1-851a-99b47d3ab92b")]
            public virtual Ranorex.CheckBox MCbAutoTypeEnabled
            {
                get
                {
                    return _mcbautotypeenabledInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The MCbAutoTypeEnabled item info.
            /// </summary>
            [RepositoryItemInfo("1872ec34-2555-48a1-851a-99b47d3ab92b")]
            public virtual RepoItemInfo MCbAutoTypeEnabledInfo
            {
                get
                {
                    return _mcbautotypeenabledInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("996c1bee-0a46-4380-9e29-2f408d726df3")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("996c1bee-0a46-4380-9e29-2f408d726df3")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }

            /// <summary>
            /// The MTabEntry1 folder.
            /// </summary>
            [RepositoryFolder("6347ee9c-e79b-411c-8ecf-2489d95267ce")]
            public virtual DesktopRepositoryFolders.MTabEntry1Folder MTabEntry1
            {
                get { return _mtabentry1; }
            }
        }

        /// <summary>
        /// The MTabEntry1Folder folder.
        /// </summary>
        [RepositoryFolder("6347ee9c-e79b-411c-8ecf-2489d95267ce")]
        public partial class MTabEntry1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _mtabentryInfo;
            RepoItemInfo _titleInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _mcbhidepasswordInfo;
            RepoItemInfo _mbtngenpwInfo;

            /// <summary>
            /// Creates a new MTabEntry1  folder.
            /// </summary>
            public MTabEntry1Folder(RepoGenBaseFolder parentFolder) :
                    base("MTabEntry1", "?/?/tabpage[@controlname='m_tabEntry']", parentFolder, 30000, null, false, "6347ee9c-e79b-411c-8ecf-2489d95267ce", "")
            {
                _mtabentryInfo = new RepoItemInfo(this, "MTabEntry", "", 30000, null, "438167ab-3e5c-4e2d-aec6-17eda5519581");
                _titleInfo = new RepoItemInfo(this, "Title", "?/?/text[@accessiblename='Title:']", 30000, null, "07422c8b-c51f-4b29-8c8b-64660ce70d44");
                _usernameInfo = new RepoItemInfo(this, "UserName", "?/?/text[@accessiblename='User name:']", 30000, null, "8f68cb20-fe38-4692-a695-9a619aeb212b");
                _mcbhidepasswordInfo = new RepoItemInfo(this, "MCbHidePassword", "checkbox[@controlname='m_cbHidePassword']", 30000, null, "3f814c53-a918-43d6-b8dd-a388f6aef6d9");
                _mbtngenpwInfo = new RepoItemInfo(this, "MBtnGenPw", "button[@controlname='m_btnGenPw']", 30000, null, "8da152e6-4fc6-4824-9bbc-cbf9f604180d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6347ee9c-e79b-411c-8ecf-2489d95267ce")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6347ee9c-e79b-411c-8ecf-2489d95267ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MTabEntry item.
            /// </summary>
            [RepositoryItem("438167ab-3e5c-4e2d-aec6-17eda5519581")]
            public virtual Ranorex.TabPage MTabEntry
            {
                get
                {
                    return _mtabentryInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MTabEntry item info.
            /// </summary>
            [RepositoryItemInfo("438167ab-3e5c-4e2d-aec6-17eda5519581")]
            public virtual RepoItemInfo MTabEntryInfo
            {
                get
                {
                    return _mtabentryInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("07422c8b-c51f-4b29-8c8b-64660ce70d44")]
            public virtual Ranorex.Text Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("07422c8b-c51f-4b29-8c8b-64660ce70d44")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("8f68cb20-fe38-4692-a695-9a619aeb212b")]
            public virtual Ranorex.Text UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("8f68cb20-fe38-4692-a695-9a619aeb212b")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The MCbHidePassword item.
            /// </summary>
            [RepositoryItem("3f814c53-a918-43d6-b8dd-a388f6aef6d9")]
            public virtual Ranorex.CheckBox MCbHidePassword
            {
                get
                {
                    return _mcbhidepasswordInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The MCbHidePassword item info.
            /// </summary>
            [RepositoryItemInfo("3f814c53-a918-43d6-b8dd-a388f6aef6d9")]
            public virtual RepoItemInfo MCbHidePasswordInfo
            {
                get
                {
                    return _mcbhidepasswordInfo;
                }
            }

            /// <summary>
            /// The MBtnGenPw item.
            /// </summary>
            [RepositoryItem("8da152e6-4fc6-4824-9bbc-cbf9f604180d")]
            public virtual Ranorex.Button MBtnGenPw
            {
                get
                {
                    return _mbtngenpwInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnGenPw item info.
            /// </summary>
            [RepositoryItemInfo("8da152e6-4fc6-4824-9bbc-cbf9f604180d")]
            public virtual RepoItemInfo MBtnGenPwInfo
            {
                get
                {
                    return _mbtngenpwInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
