///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validaciones recording.
    /// </summary>
    [TestModule("8277c7e3-6499-4567-af5e-0207b59ffe5c", ModuleType.Recording, 1)]
    public partial class Validaciones : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DesktopRepository repository.
        /// </summary>
        public static DesktopRepository repo = DesktopRepository.Instance;

        static Validaciones instance = new Validaciones();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validaciones()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validaciones Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'PwEntryForm.MBannerImage'", repo.PwEntryForm.MBannerImageInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.PwEntryForm.MBannerImageInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='PruebaWebinearDesktop') on item 'MainForm.PruebaWebinearDesktop'.", repo.MainForm.PruebaWebinearDesktopInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainForm.PruebaWebinearDesktopInfo, "Text", "PruebaWebinearDesktop");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Save' at 12;12.", repo.MainForm.SaveInfo, new RecordItemIndex(2));
            repo.MainForm.Save.Click("12;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
